import csv

rows = [
    # Página 6
    ["SC-0015", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "DISJUNTOR BIPOLAR 40A / 50A / 63A - DIN EUROPEU", "SOPRANO", "6 un.", "31,00"],
    ["7659", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "DISJUNTOR BIPOLAR 40A 5KA NEMA", "SOIPRANO", "9 un.", "89,00"],
    ["8099", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "DISJUNTOR BIPOLAR 45KA DIN DPS 275V", "SOPRANO", "1 un.", "170,96"],
    ["7660", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "DISJUNTOR BIPOLAR 60A 5KA NEMA", "SOIPRANO", "9 un.", "106,00"],
    ["7381", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "DISJUNTOR DIFERENCIAL - DR 2 MÓDULOS 30MA 230V 40A", "GE", "1 un.", "156,00"],
    ["4245", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "DISJUNTOR DIFERENCIAL - DR 2 MÓDULOS 30MA 230V 63A", "GE", "1 un.", "189,00"],
    ["SC-0016", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "DISJUNTOR TRIPOLAR 10A / 15A / 20A /25A / 30A / 35A - 5KA NEMA GE", "GE", "1 un.", "52,00"],
    ["SC-0017", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "DISJUNTOR TRIPOLAR 16A / 20A / 25A / 32A / 40A / 50A - DIN EUROPEU", "GE", "4 un.", "52,80"],
    ["7380/7359", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "DISJUNTOR TRIPOLAR 40A / 50A \"C\" PADRÃO CEMIG DIN EUROPEU", "GE", "1 un.", "63,49"],
    ["7330", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "DISJUNTOR TRIPOLAR 63A \"C\" PADRÃO CEMIG DIN EUROPEU", "GE", "1 un.", "96,80"],
    ["5477", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "DISJUNTOR TRIPOLAR 63A - DIN EUROPEU", "GE", "1 un.", "84,20"],
    ["7919", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "DISJUNTOR UNIPOLAR 20A DPS 275V - DIN EUROPEU", "SOPRANO", "1 un.", "38,90"],
    ["7351/7254", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "DISJUNTOR UNIPOLAR 40A / 50A \"C\" PADRÃO CEMIG DIN EUROPEU", "GE", "12 un.", "16,40"],
    ["5486/5516", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "DISJUNTOR UNIPOLAR 40A / 50A - DIN EUROPEU", "GE", "12 un.", "11,80"],
    ["7699/7686/7700", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "DISJUNTOR UNIPOLAR 40A / 50A / 63A - DIN EUROPEU", "SOPRANO", "12 un.", "9,70"],
    ["7681", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "DISJUNTOR UNIPOLAR 60A - 5KA NEMA", "SOPRANO", "18 un.", "35,90"],
    ["7402", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "DISJUNTOR UNIPOLAR 63A \"C\" PADRÃO CEMIG DIN EUROPEU", "GE", "12 un.", "22,30"],
    ["5472", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "DISJUNTOR UNIPOLAR 63A - DIN EUROPEU", "GE", "12 un.", "15,50"],
    ["SC-0020", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "DISJUNTOR UNIPOLAR 10A / 16A / 20A / 25A / 32A - DIN EUROPEU", "GE", "12 un.", "9,15"],
    ["SC-0018", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "DISJUNTOR UNIPOLAR 10A /15A / 20A / 25A / 30A - 5KA NEMA", "SOPRANO", "18 un.", "13,95"],
    ["SC-0021", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "DISJUNTOR UNIPOLAR 10A /16A / 20A / 25A / 32A - DIN EUROPEU", "SOPRANO", "12 un.", "8,20"],
    ["SC-0019", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "DISJUNTOR UNIPOLAR 35A / 40A / 50A - 5KA NEMA", "SOPRANO", "18 un.", "29,30"],
    ["3641", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "DIVISOR DE ANTENA/CABO COAXIAL 02 SAÍDAS", "DIVERSOS", "10 un.", "5,50"],
    ["6292", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "DIVISOR DE ANTENA/CABO COAXIAL 02 SAÍDAS 1GHZ", "INTERNEED", "1 un.", "8,70"],
    ["3642", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "DIVISOR DE ANTENA/CABO COAXIAL 03 SAÍDAS", "DIVERSOS", "10 un.", "4,95"],
    ["7234", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "DIVISOR DE ANTENA/CABO COAXIAL 03 SAÍDAS 1GHZ", "DIVERSOS", "1 un.", "11,30"],
    ["3643", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "DIVISOR DE ANTENA/CABO COAXIAL 04 SAÍDAS", "FC", "10 un.", "3,70"],
    ["7724", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "DRIVER P/PLAFON / PAINEL ATÉ 24W", "IMPORTADO", "1 un.", "8,20"],
    ["7839", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "DRIVER P/PLAFON / PAINEL ATÉ 42W", "IMPORTADO", "1 un.", "13,80"],
    ["7672", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "ELETROCALHA \"T\" HORIZONTAL 50MM x 50MM x 90º", "PERFILAÇO", "1 un.", "20,67"],
    ["7670", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "ELETROCALHA EMENDA INTERNA \"U\" 50MM x 50MM", "PERFILAÇO", "1 un.", "2,54"],
    ["7671", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "ELETROCALHA GANCHO SUPORTE VERTICAL 50MM x 50MM", "PERFILAÇO", "1 un.", "1,60"],
    ["7668", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "ELETROCALHA PERFURADA 50MM x 50MM x 03 METROS", "PERFILAÇO", "1 un.", "67,00"],
    ["6744", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "ELETRODO 6013 2,50MM C/5KILOS", "DIVERSOS", "1 un.", "82,60"],
    ["2865/2866", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "ELETRODUTO - CABEÇOTE PVC PRETO 1.1/4\" OU 1.1/2\"", "R C A", "1 un.", "3,50"],
    ["2863/2864", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "ELETRODUTO - CABEÇOTE PVC PRETO 3/4\" OU 1\"", "R C A", "1 un.", "2,70"],
    ["2876", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "ELETRODUTO - CURVA PVC \"S\" x 1\"", "R C A", "1 un.", "2,55"],

    # Página 7
    ["2878", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "ELETRODUTO - CURVA PVC \"S\" x 1.1/2\"", "R C A", "1 un.", "5,60"],
    ["2877", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "ELETRODUTO - CURVA PVC \"S\" x 1.1/4\"", "R C A", "1 un.", "4,70"],
    ["2874", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "ELETRODUTO - CURVA PVC \"S\" x 1/2\"", "R C A", "1 un.", "1,25"],
    ["2875", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "ELETRODUTO - CURVA PVC \"S\" x 3/4\"", "R C A", "1 un.", "1,60"],
    ["2871", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "ELETRODUTO - CURVA PVC 90º x 1\"", "R C A", "1 un.", "1,85"],
    ["2873", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "ELETRODUTO - CURVA PVC 90º x 1.1/2\"", "R C A", "1 un.", "3,50"],
    ["2872", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "ELETRODUTO - CURVA PVC 90º x 1.1/4\"", "R C A", "1 un.", "2,95"],
    ["2869", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "ELETRODUTO - CURVA PVC 90º x 1/2\"", "R C A", "1 un.", "0,85"],
    ["2870", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "ELETRODUTO - CURVA PVC 90º x 3/4\"", "R C A", "1 un.", "1,10"],
    ["2855", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "ELETRODUTO - LUVA P/ELETRODUTO PVC ROSCA 1\"", "R C A", "50 un.", "0,57"],
    ["2857", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "ELETRODUTO - LUVA P/ELETRODUTO PVC ROSCA 1.1/2\"", "R C A", "50 un.", "1,00"],
    ["2856", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "ELETRODUTO - LUVA P/ELETRODUTO PVC ROSCA 1.1/4\"", "R C A", "50 un.", "0,87"],
    ["2853", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "ELETRODUTO - LUVA P/ELETRODUTO PVC ROSCA 1/2\" (C/20UNDS)", "R C A", "1 un.", "8,90"],
    ["2854", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "ELETRODUTO - LUVA P/ELETRODUTO PVC ROSCA 3/4\" (C/20UNDS)", "R C A", "1 un.", "10,00"],
    ["96", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "EMENDA \"F\" P/CABO COAXIAL", "DIVERSOS", "1 un.", "0,58"],
    ["7200", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "EMENDA COTOVELO 90º P/FITA DE LED 127V/220V", "IMPORTADO", "1 un.", "9,95"],
    ["6076", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "EMENDA P/CABO HDMI", "DIVERSOS", "1 un.", "7,30"],
    ["7588/6514", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "EMENDA P/FITA DE LED 12V OU EMENDA P/FITA DE LED 127V/220V", "IMPORTADO", "1 un.", "2,60"],
    ["5623", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "ESCOVA DE AÇO C/CABO PLÁSTICO C/24CM", "FERTAK", "1 un.", "5,90"],
    ["3765", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "ESPÁTULA AÇO CROMADO C/CABO PRETO 10,00CM", "ATLAS", "12 un.", "13,80"],
    ["4814", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "ESPÁTULA AÇO CROMADO C/CABO PRETO 12,50CM", "ATLAS", "12 un.", "16,20"],
    ["4234", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "ESPÁTULA AÇO CROMADO C/CABO PRETO 3,5CM", "ATLAS", "12 un.", "10,50"],
    ["3763", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "ESPÁTULA AÇO CROMADO C/CABO PRETO 6,0CM", "ATLAS", "12 un.", "10,90"],
    ["3764", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "ESPÁTULA AÇO CROMADO C/CABO PRETO 7,50CM", "ATLAS", "12 un.", "12,20"],
    ["7907", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "ESPÁTULA CABO PLÁSTICO 06CM AÇO", "FERTAK", "12 un.", "5,20"],
    ["7908", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "ESPÁTULA CABO PLÁSTICO 08CM AÇO", "FERTAK", "12 un.", "5,40"],
    ["7909", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "ESPÁTULA CABO PLÁSTICO 10CM AÇO", "FERTAK", "12 un.", "5,70"],
    ["7910", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "ESPÁTULA CABO PLÁSTICO 12CM AÇO", "FERTAK", "12 un.", "6,20"],
    ["6996", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "ESQUADRO DE AÇO C/CABO DE ALUMÍNIO 12\" x 25CM", "FERTAK", "1 un.", "9,90"],
    ["2331", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "EXTENSÃO ELÉTRICA C/PINO C/GRADE S/LÂMPADA 127V 05MTS", "DIVERSOS", "1 un.", "41,80"],
    ["2457", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "EXTENSÃO ELÉTRICA CABO PP 2x0,75MM C/03TOMADAS 03MTS PRETA", "F.C.", "25 un.", "17,50"],
    ["2458", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "EXTENSÃO ELÉTRICA CABO PP 2x0,75MM C/03TOMADAS 05MTS PRETA", "F.C.", "25 un.", "24,60"],
    ["2459", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "EXTENSÃO ELÉTRICA CABO PP 2x0,75MM C/03TOMADAS 10MTS PRETA", "F.C.", "25 un.", "41,80"],
    ["7149", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "EXTENSÃO ELÉTRICA CABO PP 3x0,75MM C/03TOMADAS 05MTS PRETA", "F.C.", "1 un.", "33,70"],
    ["8118", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "EXTENSÃO ELÉTRICA FIO PARALELO 2x0,75MM C/03TOMADAS 03MTS PRETA", "JETCOM", "1 un.", "10,90"],
    ["8119", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "EXTENSÃO ELÉTRICA FIO PARALELO 2x0,75MM C/03TOMADAS 05MTS PRETA", "JETCOM", "1 un.", "15,70"],
    ["6922", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "EXTENSÃO ELÉTRICA FIO PARALELO 2x0,75MM C/03TOMADAS 05MTS PRETA", "F.C.", "1 un.", "21,90"],

    # Página 8
    ["8121", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "EXTENSÃO ELÉTRICA FIO PARALELO 2x0,75MM C/03TOMADAS 10MTS PRETA", "JETCOM", "1 un.", "26,90"],
    ["2330", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "EXTENSÃO P/BATERIA C/GARRA C/GRADE S/LÂMPADA 12V 05MTS", "DIVERSOS", "1 un.", "38,80"],
    ["8112", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "FACÃO C/CABO DE PLÁSTICO 18\"", "FERTAK", "1 un.", "24,43"],
    ["3985", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "FECHADURA HDL ELÉTRICA C-90 DUPLA 12V", "H D L", "1 un.", "329,00"],
    ["5882", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "FILTRO DE LINHA C/03 TOMADAS 1.00METRO 10A", "FIOLUX", "1 un.", "24,20"],
    ["5884", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "FILTRO DE LINHA C/04 TOMADAS 1.00METRO 10A", "FIOLUX", "1 un.", "25,90"],
    ["6258", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "FILTRO DE LINHA C/05 TOMADAS 1.00METRO 10A", "FIOLUX", "1 un.", "27,30"],
    ["5883", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "FILTRO DE LINHA C/06 TOMADAS 1.00METRO 10A", "FIOLUX", "1 un.", "29,20"],
    ["5703", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "FIO DE NYLON 2.00MM x 10MTS P/ROÇADEIRA e APARADOR", "BRASFORT", "1 un.", "6,20"],
    ["931", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "FITA AUTOFUSÃO 02MTS", "3M", "1 un.", "11,30"],
    ["161", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "FITA AUTOFUSÃO 10MTS", "3M", "1 un.", "52,50"],
    ["8032/8033", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "FITA DE LED 127V 9W 6.000K LUZ FRIA 120LEDS P/METRO OU 3000K LUZ QUENTE 120LEDS P/METRO", "KIAN", "50 un.", "7,70"],
    ["7589", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "FITA DE LED 12V 4,5W 6.000K LUZ FRIA C/5MTS 60LEDS POR METRO", "IMPORTADO", "1 un.", "49,90"],
    ["816", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "FITA ISOLANTE 05MTS x 18MM IMPERIAL 3M", "3M", "10 un.", "3,20"],
    ["7731", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "FITA ISOLANTE 05MTS x 18MM KORETECH", "KORETECH", "10 un.", "1,10"],
    ["8063", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "FITA ISOLANTE 05MTS x 19.00MM MEGA", "MEGA", "10 un.", "1,29"],
    ["3416", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "FITA ISOLANTE 05MTS x 19MM SCOTH 33+", "3M", "108 un.", "9,50"],
    ["817", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "FITA ISOLANTE 10MTS x 18MM IMPERIAL 3M", "3M", "10 un.", "5,60"],
    ["7732", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "FITA ISOLANTE 10MTS x 18MM KORETECH", "KORETECH", "10 un.", "1,65"],
    ["8064", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "FITA ISOLANTE 10MTS x 19.00MM MEGA", "MEGA", "10 un.", "1,80"],
    ["SC-0025", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "FITA ISOLANTE 10MTS x 19MM AMARELA / AZUL / BRANCA / VERDE / VERMELHA", "DIVERSOS", "10 un.", "2,70"],
    ["818", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "FITA ISOLANTE 20MTS x 18MM IMPERIAL 3M", "3M", "10 un.", "8,30"],
    ["7798", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "FITA ISOLANTE 20MTS x 18MM KORETECH", "KORETECH", "10 un.", "3,60"],
    ["8034", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "FITA ISOLANTE 20MTS x 19.00MM MEGA", "MEGA", "10 un.", "4,10"],
    ["649", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "FITA ISOLANTE 20MTS x 19MM SCOTH 33+", "3M", "150 un.", "31,90"],
    ["4420", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "FONTE DE ALIMENTAÇÃO 127V / 220V P/ 12V TRA400", "H D L", "1 un.", "106,70"],
    ["5649", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "FONTE DE ALIMENTAÇÃO UNIVERSAL PRETO 30W", "DIVERSOS", "1 un.", "57,70"],
    ["7303", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "FONTE ELETRÔNICA BIVOLT P/12V C/PINO P4", "M X T", "1 un.", "15,88"],
    ["7496", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "FORMÃO C/CABO DE MADEIRA 1\" - (25MM)", "FERTAK", "1 un.", "14,40"],
    ["7495", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "FORMÃO C/CABO DE MADEIRA 3/4\" - (20MM)", "FERTAK", "1 un.", "13,60"],
    ["7494", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "FORMÃO C/CABO DE MADEIRA 5/8\" - (16MM)", "FERTAK", "1 un.", "12,90"],
    ["7694", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "FUSÍVEL CERÂMICO P/MICRO-ONDAS 6 x 30MM 20A", "IMPORTADO", "1 un.", "1,60"],
    ["SC-0026", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "FUSÍVEL DE VIDRO PEQUENO 3A / 5A / 10A / 15A (C/50 PEÇAS)", "DIVERSOS", "1 un.", "19,80"],
    ["7023/7022", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "GARRA JACARÉ GRANDE 300A 135MM PRETA / VERMELHA", "DIVERSOS", "1 un.", "10,30"],
    ["6932/6934", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "GARRA JACARÉ MÉDIA 100A 105MM PRETA / VERMELHA", "DIVERSOS", "1 un.", "5,20"],
    ["6740/6741", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "GARRA JACARÉ PEQUENA 15A 75MM PRETA / VERMELHA", "DIVERSOS", "1 un.", "1,30"],
    ["6640/2488/2602", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "GRAMPO CLAMP DE FIXAÇÃO TV-04 OU TV-06 OU TV08 BRANCO C/10UNDS", "RIB. FABRIL", "50 un.", "2,00"]
]

with open('public/modelos/material_eletrico_pampulha.csv', 'a', encoding='utf-8', newline='') as f:
    writer = csv.writer(f)
    writer.writerows(rows)

print(f"Páginas 6 a 8 adicionadas: {len(rows)} itens.")
