import csv

rows = [
    # Página 9
    ["1243/1244", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "GRAMPO DE FIXAÇÃO P/CABO COAXIAL C/PREGO COMUM C/15UNDS BRANCO OU PRETO", "RIB. FABRIL", "50 un.", "2,90"],
    ["6536", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "GRAMPO DE FIXAÇÃO P/CABO COAXIAL C/PREGO DE AÇO C/15UNDS BRANCO", "RIB. FABRIL", "50 un.", "5,50"],
    ["6365", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "GRAMPO DE FIXAÇÃO P/FIO PARALELO 1,50MM C/15UNDS BRANCO", "RIB. FABRIL", "50 un.", "2,90"],
    ["1573/1572", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "GRAMPO MIGUELÃO C/PREGO COMUM C/15UNDS BRANCO OU MARROM", "RIB. FABRIL", "50 un.", "2,50"],
    ["6534/6689", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "GRAMPO MIGUELÃO C/PREGO DE AÇO C/15UNDS BRANCO OU MARROM", "RIB. FABRIL", "50 un.", "4,30"],
    ["6309", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "GRAMPO P/FIXAÇÃO CABO RG6 16MM BRANCO C/15UNDS", "RIB. FABRIL", "35 un.", "3,20"],
    ["6535", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "GRAMPO P/FIXAÇÃO CABO RG6 16MM C/PREGO DE AÇO BRANCO C/15UNDS", "RIB. FABRIL", "35 un.", "5,20"],
    ["6972", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "GRAMPO P/FIXAÇÃO CABO RG6 8MM BRANCO C/100UNDS", "DIVERSOS", "1 un.", "8,30"],
    ["5865", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "HASTE P/CERCA ELÉTRICA GALVANIZADA C/04 ISOLADORES", "MC GARCIA", "1 un.", "24,00"],
    ["2416", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "HASTE TERRA GALVANIZADA TIPO CANTONEIRA C/CONECTOR 2,40MTS P/PADRÃO", "DIVERSOS", "5 un.", "86,80"],
    ["962", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "INTERRUPTOR BIPOLAR 1SECÇÃO S/PLACA 20A", "PERLEX", "1 un.", "16,40"],
    ["4320", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "INTERRUPTOR CAMPAINHA C/PLACA PIAL NEREYA", "PIAL", "1 un.", "7,90"],
    ["2127", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "INTERRUPTOR CAMPAINHA EXTERNO RETANGULAR BRANCO", "PERLEX", "40 un.", "8,50"],
    ["2076", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "INTERRUPTOR EXTERNO RETANGULAR 1SEÇÃO SIMPLES BRANCO", "PERLEX", "40 un.", "6,30"],
    ["2289", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "INTERRUPTOR EXTERNO RETANGULAR 1SEÇÃO TRIWÊ BRANCO", "PERLEX", "40 un.", "8,20"],
    ["5103", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "INTERRUPTOR EXTERNO RETANGULAR 1SEÇÃO+TOMADA 20A BRANCO", "PERLEX", "20 un.", "11,30"],
    ["1538", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "INTERRUPTOR EXTERNO RETANGULAR 2SEÇÃO SIMPLES BRANCO", "PERLEX", "40 un.", "9,60"],
    ["3171", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "INTERRUPTOR MEIO FIO BRANCO", "PERLEX", "40 un.", "4,90"],
    ["3920", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "INTERRUPTOR P/VENITLADOR DE TETO C/TECLA + CAPACITOR", "MARGIRIUS", "1 un.", "44,40"],
    ["7011", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "INTERRUPTOR P/VENTILADOR DE EMBUTIR C/CAPACITOR", "APLACEL", "1 un.", "25,20"],
    ["7012", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "INTERRUPTOR P/VENTILADOR DE EMBUTIR S/CAPACITOR", "APLACEL", "1 un.", "19,40"],
    ["7800", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "ISOLADOR DE PORCELANA 72 x 54 ( PIMENTÃO )", "FERTAK", "12 un.", "7,90"],
    ["2495", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "ISOLADOR P/HASTE EM PVC P/CERCA ELÉTRICA", "DIVERSOS", "1 un.", "2,70"],
    ["7480", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "ISOLADOR PINO RESERVA P/BARRAMENTO 05PÓLOS", "ENERBRÁS", "1 un.", "4,80"],
    ["7586", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "LIMA CHATA P/ENXADA 8\" C/CABO PLÁSTICO", "K&F", "1 un.", "17,70"],
    ["8049", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "LIZ BRANCA INTERRUPTOR 1S SIMPLES + TOMADA 10A C/PLACA 57170264", "TRAMONTINA", "120 un.", "16,90"],
    ["7956", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "LIZ BRANCA INTERRUPTOR 1S SIMPLES C/PLACA 57170201", "TRAMONTINA", "120 un.", "10,70"],
    ["7950", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "LIZ BRANCA MÓDULO CAMPAINHA BIVOLT 57115063", "TRAMONTINA", "5 un.", "53,00"],
    ["7948/7949", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "LIZ BRANCA MÓDULO CEGO 57115090 OU MÓDULO SAÍDDA DE FIO 57115003", "TRAMONTINA", "50 un.", "1,00"],
    ["7951", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "LIZ BRANCA MÓDULO INT 1 SEÇÃO 57115010", "TRAMONTINA", "50 un.", "6,20"],
    ["7952", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "LIZ BRANCA MÓDULO INT 1 SEÇÃO TRIWE 57115008", "TRAMONTINA", "50 un.", "9,70"],
    ["7954", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "LIZ BRANCA MÓDULO INT BIPOLAR 10A 57115004", "TRAMONTINA", "10 un.", "21,90"],
    ["7955", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "LIZ BRANCA MÓDULO INT CAMPAIINHA 57115027", "TRAMONTINA", "10 un.", "8,20"],
    ["7953", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "LIZ BRANCA MÓDULO INT INTERMEDIÁRIO 57115003", "TRAMONTINA", "10 un.", "22,20"],
    ["7959", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "LIZ BRANCA MÓDULO MÓDULO ANTENA/TV", "TRAMONTINA", "10 un.", "7,45"],
    ["7957", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "LIZ BRANCA MÓDULO TOMADA 3P 10A 57115040", "TRAMONTINA", "50 un.", "6,70"],
    ["7958/7962", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "LIZ BRANCA MÓDULO TOMADA 3P 20A BRANCA OU TOMADA 3P 20A VERMELHA", "TRAMONTINA", "50 un.", "7,45"],

    # Página 10
    ["SC-0046", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "LIZ BRANCA PLACA 2 x 4 C/SUPORTE (DIVERSOS MODELOS)", "TRAMONTINA", "20 un.", "5,30"],
    ["SC-0047", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "LIZ BRANCA PLACA 4 x 4 C/SUPORTE (DIVERSOS MODELOS)", "TRAMONTINA", "20 un.", "11,50"],
    ["8050", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "LIZ BRANCA TOMADA 3P 10A DUPLA C/PLACA 57170265", "TRAMONTINA", "120 un.", "17,50"],
    ["7960", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "LIZ BRANCA TOMADA 3P 10A HORIZONTAL C/PLACA 57170210", "TRAMONTINA", "120 un.", "9,40"],
    ["8051", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "LIZ BRANCA TOMADA 3P 20A DUPLA C/PLACA 57170266", "TRAMONTINA", "120 un.", "18,20"],
    ["7961", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "LIZ BRANCA TOMADA 3P 20A HORIZONTAL C/PLACA 57170213", "TRAMONTINA", "120 un.", "11,80"],
    ["7428", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "LUIBRIFICANTE P/PUXAMENTO DE FIOS/CABOS 200ML", "3 M", "12 un.", "22,80"],
    ["5833", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "LUMINÁRIA ALETADA P/02 LÂMPADAS LED 18W / 20W", "UTRON", "1 un.", "54,80"],
    ["5832", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "LUMINÁRIA ALETADA P/02 LÂMPADAS LED 9W / 10W", "UTRON", "1 un.", "34,40"],
    ["5409/5415", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "LUMINÁRIA ALTO RENDIMENTO P/LED 2x18W OU C/04LÂMPADAS E-27 P/EMBUTIR", "BLUMENAU", "1 un.", "19,90"],
    ["5544/5543", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "LUMINÁRIA COLONIAL P/PAREDE C/BRAÇO OU P/TETO C/CORRENTE", "DIVERSOS", "1 un.", "39,00"],
    ["6280", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "LUMINÁRIA CÔNICA P/01 LÂMPADA ROSCA E-27", "DIVERSOS", "1 un.", "45,70"],
    ["7497", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "LUMINÁRIA DE EMERGÊNCIA 30 LEDS", "SEGURIMAX", "1 un.", "19,50"],
    ["8031", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "LUMINÁRIA DE MESA FLEXÍVEL E-27 PRETA", "KIAN", "1 un.", "44,00"],
    ["8036", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "LUMINÁRIA LED 18W SLIM BRANCA BIVOLT 50CM 1.400 LUMENS", "DIVERSOS", "1 un.", "13,90"],
    ["8037", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "LUMINÁRIA LED 36W SLIM BRANCA 1.00MTS 2.600 LUMENS", "DIVERSOS", "1 un.", "18,90"],
    ["7051", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "LUMINÁRIA LED 36W SLIM BRANCA 1.20MTS 2.800 LUMENS", "LEDVANCE", "1 un.", "18,40"],
    ["3234", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "LUMINÁRIA OVAL ABERTA DE ALUMÍNIO C/SOQUETE DE LOUÇA E-27 3/4\"", "DIVERSOS", "1 un.", "36,80"],
    ["4374", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "LUMINÁRIA PENDENTE PRISMÁTICA CRISTAL 12\" P/01 LÂMPADA ROSCA E-27", "UTRON", "1 un.", "68,70"],
    ["7527", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "LUMINÁRIA PENDENTE PRISMÁTICA CRISTAL 16\" P/01 LÂMPADA ROSCA E-27", "UTRON", "1 un.", "116,80"],
    ["5686/5520", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "LUMINÁRIA PENDENTE TULIPA P/01LÂMPADA E-27 C/CÚPULA PRETA OU VERMELHA", "BLUMENAU", "1 un.", "89,90"],
    ["6952/6951", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "LUMINÁRIA TARTARUGA CHAPA C/LENTE DE ACRÍLICO BRANCA OU PRETA", "JR", "15 un.", "14,60"],
    ["7218", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "LUMINÁRIA TARTARUGA LED 15W BIVOLT 6.000K BRANCA 1.100 LM", "DIVERSOS", "1 un.", "22,50"],
    ["6817", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "LUMINÁRIA TARTARUGA LED 5W BIVOLT 6.500K BRANCA 420 LM", "AVANT", "1 un.", "17,80"],
    ["5721/6049", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "LUMINÁRIA TARTARUGA POLICARBONATO GRANDE BRANCA OU PRETA", "LALUX", "50 un.", "13,70"],
    ["6283", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "LUMINÁRIA TRIANGULAR GRANDE P/02 LÂMPADAS ROSCA E-27", "FÁB. DA LUZ", "1 un.", "93,40"],
    ["7026", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "LUMINÁRIA TRIANGULAR MÉDIA P/01 LÂMPADA ROSCA E-27", "FÁB. DA LUZ", "1 un.", "79,80"],
    ["6281", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "LUMINÁRIA TRIANGULAR PEQUENA P/01 LÂMPADA ROSCA E-27", "FÁB. DA LUZ", "1 un.", "51,00"],
    ["7378/7379", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "LUZ GUIA LED BARCO 127V AZUL OU LUZ GUIA BORBOELTA LED 127V ROSA", "BRASFORT", "1 un.", "13,80"],
    ["SC-0028", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "LÂMPADA BOLINHA COLORIDA 15W x 127V (AM/AZ/CLARA/LEITOSA/VD/VM )", "DIVERSOS", "25 un.", "3,95"],
    ["3597", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "LÂMPADA CHUPETA ROSCA E - 12 7W x 127V CLARA", "DIVERSOS", "50 un.", "2,70"],
    ["SC-0029", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "LÂMPADA CHUPETA ROSCA E - 14 7W x 127V ( AM, AZ, CLARA, VD, VM )", "DIVERSOS", "50 un.", "2,30"],
    ["5002", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "LÂMPADA DICROICA HALÓGENA 50W x 127V GU10", "KIAN", "10 un.", "11,50"],
    ["5773/3833", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "LÂMPADA ESPIRAL COMPACTA 14W x 127V AMARELA / VERMELHA", "TASCHIBRA", "10 un.", "19,80"],
    ["6457/1676", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "LÂMPADA FREEZER / MICRO-ONDAS ROSCA E-14 15W x 127V OU 15W 220V", "KIAN", "50 un.", "2,95"],
    ["0233/6177", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "LÂMPADA GELADEIRA / FOGÃO 40W x 127V ROSCA E-27 CLARA OU LEITOSA", "BRASFORT", "10 un.", "3,90"],
    ["SC-0030", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "LÂMPADA HALÓGENA ( PALITO ) 150W / 300W / 500W 127V ou 220V", "DIVERSOS", "10 un.", "7,40"],

    # Página 11
    ["6139/6140", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "LÂMPADA HALÓGENA ROSCA E-27 100W x 127V / 100W x 220V", "DIVERSOS", "10 un.", "5,40"],
    ["5796/2531", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "LÂMPADA HALÓGENA ROSCA E-27 70W x 127V OU LÂMPADA GELADEIRA 40W x 220V", "DIVERSOS", "10 un.", "5,30"],
    ["1817", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "LÂMPADA INCANDESCENTE BAIXA VOLTAGEM ROSCA E-27 40W x 12V", "BRASFORT", "10 un.", "7,30"],
    ["7432", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "LÂMPADA LED 20W SUPERLED 6.500K LUZ FRIA 1.800 LUMENS", "DIVERSOS", "10 un.", "5,70"],
    ["7451", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "LÂMPADA LED 30W SUPERLED 6.500K LUZ FRIA 2.400 LUMENS", "DIVERSOS", "10 un.", "9,60"],
    ["6829", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "LÂMPADA LED 40W SUPERLED 6500K LUZ FRIA 4.000 LUMENS", "DIVERSOS", "10 un.", "12,30"],
    ["7901", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "LÂMPADA LED 50W SUPERLED 6.500K LUZ FRIA 4.000 LUMENS", "DIVERSOS", "1 un.", "16,50"],
    ["7458", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "LÂMPADA LED 65W SUPERLED 6.500K LUZ FRIA 5.850 LUMENS", "DIVERSOS", "1 un.", "48,30"],
    ["7904", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "LÂMPADA LED 80W SUPERLED 6.500K LUZ FRIA 6.400 LUMENS", "DIVERSOS", "1 un.", "63,20"],
    ["7071", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "LÂMPADA LED A-60 12W BIVOLT E-27 6500K LUZ FRIA1.080 LUMENS", "DIVERSOS", "10 un.", "4,40"],
    ["6381", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "LÂMPADA LED A-60 15W BIVOLT E-27 6500K LUZ FRIA 1.350 LUMENS", "BLUMENAU", "10 un.", "4,95"],
    ["7619", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "LÂMPADA LED A-60 4W RETRÔ BIVOLT 2.400K - VINTAGE", "KIAN", "1 un.", "13,30"],
    ["7979", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "LÂMPADA LED A-60 9W BIVOLT E-27 3000K LUZ QUENTE 803 LUMENS", "DIVERSOS", "10 un.", "2,80"],
    ["8106", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "LÂMPADA LED A-60 9W BIVOLT E-27 6500K LUZ FRIA 803 LUMENS AURELED", "AURELED", "10 un.", "2,70"],
    ["7934", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "LÂMPADA LED A-60 9W BIVOLT E-27 PRETA 882 LUMENS", "KIAN", "1 un.", "36,80"],
    ["7968", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "LÂMPADA LED A-60 9W BIVOLT ROSCA E-27 AMARELA - ANTI-INSETO", "KIAN", "1 un.", "10,70"],
    ["7973", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "LÂMPADA LED A-70 17W SUPERLED 6.500K LUZ FRIA 1.521 LUMENS", "LEDVANCE", "10 un.", "11,16"],
    ["7801", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "LÂMPADA LED BAIXA VOLTAGEM E-27 7W x 12V", "KIAN", "10 un.", "13,40"],
    ["SC-0031", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "LÂMPADA LED BOLINHA 1W BIVOLT AMARELA / AZUL / VERDE / VERMELHA", "IMPORTADO", "10 un.", "10,90"],
    ["6763", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "LÂMPADA LED BOLINHA 3W BIVOLT BRANCA", "DIVERSOS", "10 un.", "10,70"],
    ["7976/7975/7974", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "LÂMPADA LED DICR. 6.5W GU10 MR16 2.700K QUENTE/ 4.000K NEUTRA / 6.500K FRIA", "KIAN", "10 un.", "8,50"],
    ["7691", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "LÂMPADA LED FREEZER/MICRO-ONDAS ROSCA E-14 3W x 127V", "FOXLUX", "1 un.", "15,70"],
    ["7821", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "LÂMPADA LED HALOPIN G9 3W 2.500K LUZ QUENTE 127V", "KIAN", "1 un.", "18,30"],
    ["7782/7779", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "LÂMPADA LED HALOPIN G9 7W 3.000K LUZ QUENTE OU 6.500K LUZ FRIA", "IMPORTADO", "1 un.", "11,40"],
    ["7977/7978", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "LÂMPADA LED MINI \"T\" 9W E-27 3.000K LUZ QUENTE / \"T\" 9W E-27 6.500K LUZ FRIA", "KIAN", "10 un.", "3,95"],
    ["5814/8165", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "LÂMPADA LED TUBO 18W/20W T-8 1.20MT 6.500K LUZ FRIA OU 3.000K LUZ QUENTE", "DIVERSOS", "25 un.", "8,70"],
    ["6210", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "LÂMPADA LED TUBO 9W/10W T-8 60CM 6.500K LUZ FRIA LUMENS 900", "DIVERSOS", "25 un.", "7,50"],
    ["7896", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "LÂMPADA LED VELA LEITOSA 4W E-14 C/ADAPTADOR E-27", "KIAN", "1 un.", "20,80"],
    ["1638/2306", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "LÂMPADA MÁQUINA DE COSTURA 15W x 127V ( ENCAIXE ) OU (ROSCA) E-14 15W x 127V", "BRASFORT", "50 un.", "4,60"],
    ["5274/5280", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "LÂMPADA PAR 20 30LEDS 2.2W x 220V OU PAR 38 90LEDS 5Wx220V BRANCA", "DIVERSOS", "1 un.", "9,90"],
    ["4435/3624", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "LÂMPADA PAR 20 50W x 220V VERDE OU PAR 38 100Wx127V VERMELHA", "DIVERSOS", "1 un.", "9,90"],
    ["5858", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "LÂMPADA PAR 20 LED 7W ROSCA E-27 BIVOLT BRANCA", "KIAN", "10 un.", "14,90"],
    ["7897", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "LÂMPADA REFLETORA 50W x 127V E-27 CLARA", "KIAN", "10 un.", "6,80"],
    ["3875/3454", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "LÂMPADA VELA LISA E-14 OU E-27 40W x 127V CLARA OU LEITOSA", "DIVERSOS", "10 un.", "4,20"],
    ["7516", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "MACHADINHA C/CABO DE FIBRA 600G", "BRASFORT", "1 un.", "77,10"],
    ["7118", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "MARTELO C/CABO DE FIBRA 27MM POLIDO", "FERTAK", "1 un.", "29,30"],
    ["4201", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "MARTELO C/CABO DE MADEIRA 27MM POLIDO", "FERTAK", "1 un.", "28,70"],

    # Página 12
    ["7849", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "MARTELO DE BORRACHA BRANCA C/CABO DE MADEIRA 60MM", "FERTAK", "1 un.", "24,50"],
    ["4965", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "MARTELO DE BORRACHA PRETA C/CABO DE MADEIRA 60MM", "DIVERSOS", "1 un.", "17,95"],
    ["2508", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "MULTÍMETRO DIGITAL", "IMPORTADO", "10 un.", "27,80"],
    ["3571/5626", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "ORGANIZADOR DE FIOS FINO 10MM C/01METRO BRANCO / PRETO", "OVERTIME", "1 un.", "3,30"],
    ["3572/3839", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "ORGANIZADOR DE FIOS FINO C/25METROS BRANCO / PRETO", "OVERTIME", "1 un.", "61,40"],
    ["6338/6339", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "ORGANIZADOR DE FIOS GROSSO 16MM C/01METRO BRANCO / PRETO", "OVERTIME", "1 un.", "4,60"],
    ["6340/6869", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "ORGANIZADOR DE FIOS GROSSO C/25METROS BRANCO / PRETO", "OVERTIME", "1 un.", "89,80"],
    ["7111", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "PAINEL LED QUADRADO EMBUTIR 12W 6.500K LUZ FRIA 1.200 LM", "DIVERSOS", "1 un.", "13,80"],
    ["7390/7744", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "PAINEL LED QUADRADO EMBUTIR 18W 6.500K LUZ FRIA / 18W 3000K LUZ QUENTE 1.332 LM", "DIVERSOS", "1 un.", "15,50"],
    ["8166", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "PAINEL LED QUADRADO EMBUTIR 24W 3.000K LUZ QUENTE 1.800 LM", "DIVERSOS", "1 un.", "21,80"],
    ["7391", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "PAINEL LED QUADRADO EMBUTIR 24W 6.500K LUZ FRIA 1.776 LM", "DIVERSOS", "1 un.", "19,90"],
    ["7392", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "PAINEL LED QUADRADO EMBUTIR 36W 6.500K LUZ FRIA 3.420 LM", "DIVERSOS", "1 un.", "76,80"],
    ["7532", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "PENDENTE ALÚMINIO BRANCO C/COBRE 16\"", "UTRON", "1 un.", "170,90"],
    ["6355/6356", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "PENDENTE COMPLETO P/LUSTRE 1MT ROSCA E-27 BRANCO / PRETO", "MARCAI", "1 un.", "16,50"],
    ["7528", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "PENDENTE TRIO PRETO C/COBRE C/03 BOCAL ROSCA E-27", "UTRON", "1 un.", "155,90"],
    ["7314", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "PIAL POP INT 1 SEÇÃO + TOMADA 10A C/PLACA LGX103", "PIAL", "10 un.", "14,80"],
    ["7289", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "PIAL POP INT 1 SEÇÃO SIMPLES C/PLACA HORIZONTAL LGX010", "PIAL", "10 un.", "6,20"],
    ["7574", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "PIAL POP INT 1 SEÇÃO TRIWE C/PLACA HORIZONTAL LGX020", "PIAL", "10 un.", "9,50"],
    ["7321", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "PIAL POP MÓDULO CAMPAINHA 127V LG0701C", "PIAL", "5 un.", "29,90"],
    ["7278", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "PIAL POP MÓDULO INT 1 SEÇÃO SIMPLES LG010", "PIAL", "10 un.", "5,15"],
    ["7279", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "PIAL POP MÓDULO INT 1 SEÇÃO TRIWE LG020", "PIAL", "10 un.", "6,20"],
    ["7298", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "PIAL POP MÓDULO INT BIPOLAR 10A LG010B", "PIAL", "10 un.", "14,90"],
    ["7331", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "PIAL POP MÓDULO INT CAMPAINHA 2A LG040", "PIAL", "10 un.", "5,30"],
    ["7280", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "PIAL POP MÓDULO INT INTERMEDIÁRIO LG020I", "PIAL", "5 un.", "22,80"],
    ["7575", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "PIAL POP MÓDULO MÓDULO CEGO LG000", "PIAL", "10 un.", "3,90"],
    ["7281", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "PIAL POP MÓDULO SAÍDA DE ANTENA LG060", "PIAL", "5 un.", "13,40"],
    ["7285", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "PIAL POP MÓDULO SAÍDA DE FIO LG20F", "PIAL", "10 un.", "3,40"],
    ["7282", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "PIAL POP MÓDULO TOMADA 3P 10A LG030", "PIAL", "10 un.", "6,40"],
    ["7283", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "PIAL POP MÓDULO TOMADA 3P 20A LG03020", "PIAL", "10 un.", "7,20"],
    ["7618", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "PIAL POP MÓDULO TOMADA 3P 20A LG03020VM VERMELHO", "PIAL", "1 un.", "10,50"],
    ["SC-0048", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "PIAL POP PLACA 2 X 4 (DIVERSOS MODELOS)", "PIAL", "10 un.", "3,70"],
    ["SC-0049", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "PIAL POP PLACA 4 X 4 (DIVERSOS MODELOS)", "PIAL", "10 un.", "7,90"],
    ["7277", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "PIAL POP TOMADA 3P 10A C/PLACA HORIZONTAL LGX030", "PIAL", "10 un.", "8,40"],
    ["7319", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "PIAL POP TOMADA 3P 20A C/PLACA HORIZONTAL LGX03020", "PIAL", "10 un.", "10,30"],
    ["5406", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "PINO 3SAIDAS UNIVERSAL BRANCO", "IMPORTADO", "1 un.", "2,99"],
    ["5202", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "PINO ADAPT MULTIPLO P/TOMADA UNIVERSAL (BOB)", "IMPORTADO", "1 un.", "2,00"],
    ["7369", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "PINO ADAPTADOR 2P + T UNIVERSAL BRANCO", "PERLEX", "10 un.", "5,40"]
]

with open('public/modelos/material_eletrico_pampulha.csv', 'a', encoding='utf-8', newline='') as f:
    writer = csv.writer(f)
    writer.writerows(rows)

print(f"Páginas 9 a 12 adicionadas: {len(rows)} itens.")
