import csv

rows = [
    # Página 2
    ["SC-0001", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CANALETA 40 x 15 - CONEXÕES (COTOVELOS 90º/INT./EXT./\"T\"/LUVA e LUVA P/PONTA)", "ENERBRAS", "25 un.", "2,60"],
    ["8048", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CANALETA 40 x 15 2MTS BRANCA C/FITA DUPLA FACE", "ENEREBRÁS", "10 un.", "21,90"],
    ["5571", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CANALETA 40 x 16 2MTS BRANCA C/FITA DUPLA FACE", "PERLEX", "10 un.", "19,40"],
    ["SC-0002", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CANALETA 50 x 20 - CONEXÕES (COTOVELOS 90º/INT./EXT./\"T\"/LUVA e LUVA P/PONTA)", "ENERBRAS", "25 un.", "3,70"],
    ["7514", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CANALETA 50 x 20 2MTS BRANCA C/FITA DUPLA FACE", "ENERBRAS", "7 un.", "48,90"],
    ["2342", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CANALETA 50 x 20 2MTS BRANCA S/FITA DUPLA FACE", "ENERBRÁS", "7 un.", "28,90"],
    ["6422", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CANALETA P/PISO 52CM x 14CM 2MTS S/FITA DUPLA FACE", "ENERBRAS", "7 un.", "55,40"],
    ["8141", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CAPACITOR P/PORTÃO ELETRÔNICO 250V x 25UF", "DIVERSOS", "1 un.", "14,90"],
    ["6384/7785/6387", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CAPACITOR P/VENTILADOR 250V x 3UF + 7UF OU 250V x 4UF + 6UF OU 250V x 12UF", "DIVERSOS", "1 un.", "12,70"],
    ["6385/7784/6386", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CAPACITOR P/VENTILADOR 250V x 6UF OU 250V x 8UF OU 250V x 10UF", "DIVERSOS", "1 un.", "8,90"],
    ["1483/1482", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CHAVE BIPOLAR 10A CS-301C OU CHAVE BIPOLAR 15A CS-301B", "MAR-GIRIUS", "1 un.", "52,80"],
    ["1490/1491", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CHAVE BIPOLAR 15A 14201 OU CHAVE BIPOLAR 15A C/PONTO MORTO 14203", "MAR-GIRIUS", "1 un.", "69,00"],
    ["6183", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CHAVE BIPOLAR 15A ALVANCA CROMADA 14223", "MAR-GIRIUS", "1 un.", "50,80"],
    ["1481", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CHAVE BIPOLAR 20A CS-301A", "MAR-GIRIUS", "1 un.", "55,80"],
    ["1728", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CHAVE BIPOLAR 3A MICRO ALAVANCA METAL 17201", "MAR-GIRIUS", "1 un.", "29,00"],
    ["6116", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CHAVE BÓIA 1 x 25A 250V INFERIOR / SUPERIOR CB-3001", "MAR-GIRIUS", "1 un.", "54,40"],
    ["1738/1739", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CHAVE MICRO HASTE CURTA 20A MG2605 OU HASTE CURTA C/RODIZIO 20A MG2606", "MAR-GIRIUS", "1 un.", "34,40"],
    ["1736/1737", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CHAVE MICRO HASTE LONGA 20A MG2603 OU HASTE LONGA C/RODIZIO 20A MG2604", "MAR-GIRIUS", "1 un.", "56,40"],
    ["1741/1742", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CHAVE MICRO PINO 15A A1 40108 OU CHAVE MICRO C/HASTE 15A A2 40108", "MAR-GIRIUS", "1 un.", "26,50"],
    ["1735", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CHAVE MICRO PINO BÁSICO 20A MG2601", "MAR-GIRIUS", "1 un.", "24,20"],
    ["1740", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CHAVE MICRO PINO BÁSICO 20A MG2607", "MAR-GIRIUS", "1 un.", "51,80"],
    ["1722", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CHAVE PORTA FUSÍVEL - ROSCA 20AG 11005/F", "MAR-GIRIUS", "1 un.", "11,60"],
    ["1499", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CHAVE REVERSÃO TRIPOLAR 15A CR-501K", "MAR-GIRIUS", "1 un.", "117,80"],
    ["5206", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CHAVE REVERSÃO TRIPOLAR 30A CR-603-03/F", "MAR-GIRIUS", "1 un.", "155,80"],
    ["3430", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CHAVE TESTE COMUM", "FERTAK", "12 un.", "1,90"],
    ["6875", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CHAVE TESTE DIGITAL", "MEGA", "1 un.", "5,50"],
    ["1264", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CHAVE TESTE/CONTINUIDADE/TENSÃO", "DIVERSOS", "1 un.", "12,80"],
    ["4358", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CHAVE TOMADA DE PAINEL C/3PÓLOS 10A TPA2", "MAR-GIRIUS", "1 un.", "7,80"],
    ["1492", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CHAVE TRIPOLAR 15A 14301", "MAR-GIRIUS", "1 un.", "114,70"],
    ["1497", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CHAVE TRIPOLAR 15A CS-501KS LIGA - DESLIGA", "MAR-GIRIUS", "1 un.", "119,60"],
    ["1477/1478", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CHAVE TRIPOLAR 20A BOTÃO PRETO/VERMELHO CS-101 OU 30A CS-101 TP/CC", "MAR-GIRIUS", "1 un.", "76,90"],
    ["2074/1948", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CHAVE TRIPOLAR 20A BOTÃO PRETO/VERMELHO CS-102TS OU TRIPOLAR 30A CS-102TP", "MAR-GIRIUS", "1 un.", "59,40"],
    ["1479", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CHAVE TRIPOLAR 20A CS-301", "MAR-GIRIUS", "1 un.", "82,60"],
    ["1480", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CHAVE TRIPOLAR 30A CS-301P", "MAR-GIRIUS", "1 un.", "72,80"],
    ["5208", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CHAVE TRIPOLAR 30A LIGA-DESLIGA CS-603", "MAR-GIRIUS", "1 un.", "131,70"],
    ["1724", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CHAVE UNIPOLAR 10A LIGA-DESLIGA 15123", "MAR-GIRIUS", "1 un.", "25,50"],
    ["1726", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CHAVE UNIPOLAR 10A TECLA REDONDA PRETA 16123", "MAR-GIRIUS", "1 un.", "12,40"],

    # Página 3
    ["1495", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CHAVE UNIPOLAR 10A TECLA RETANGULAR PRETA 16123", "MAR-GIRIUS", "1 un.", "8,80"],
    ["1488", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CHAVE UNIPOLAR 15A 14101", "MAR-GIRIUS", "1 un.", "41,00"],
    ["1494", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CHAVE UNIPOLAR 15A 14123", "MAR-GIRIUS", "1 un.", "47,40"],
    ["1489", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CHAVE UNIPOLAR 15A COM PONTO MORTO 14103", "MAR-GIRIUS", "1 un.", "59,80"],
    ["1898", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CHAVE UNIPOLAR 3A MFTFE 16103", "MAR-GIRIUS", "1 un.", "10,70"],
    ["1727/1725", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CHAVE UNIPOLAR 3A MICRO ALAV. METAL 17101 OU CHAVE UNIP. 6A LIGA/DESL VERMELHA 16123", "MAR-GIRIUS", "1 un.", "22,60"],
    ["1496/1744", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CHAVE UNIPOLAR 6A PAINEL 20123 OU CHAVE UNIPOLAR 3A PULSADOR 20127", "MAR-GIRIUS", "1 un.", "13,40"],
    ["1484", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CHAVE UNIPOLAR ALAVANCA CROMADA 6A CS-301D", "MAR-GIRIUS", "1 un.", "28,20"],
    ["1486/1485", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CHAVE UNIPOLAR ALAVANCA PRETA 6A CS-301D OU VERMELHA 6A CS-301D", "MAR-GIRIUS", "1 un.", "17,40"],
    ["1732", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CHAVE UNIPOLAR BOTÃO LIGA - DESLIGA 10A 36123", "MAR-GIRIUS", "1 un.", "18,40"],
    ["1733/1734", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CHAVE UNIPOLAR BOTÃO LIGA - DESLIGA VERDE OU VERMELHA 1A N. A. CS-390P1", "MAR-GIRIUS", "1 un.", "34,40"],
    ["1729", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CHAVE UNIPOLAR BOTÃO PEQUENO N. A . LIGA - DESLIGA 0,5A 18531", "MAR-GIRIUS", "1 un.", "19,90"],
    ["4296", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CINTA DE AÇO PERFURADA 17MM x 10MTS (FITA)", "MONTEC", "1 un.", "18,50"],
    ["7593", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CINTA DE AÇO PERFURADA 17MM x 30MTS (FITA)", "MONTEC", "1 un.", "63,80"],
    ["8137", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CLIPS P/CABO DE ACO 5/16\"", "FERTAK", "1 un.", "0,70"],
    ["6785", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CLIPS P/CABO DE AÇO 1/2\"", "FERTAK", "1 un.", "2,70"],
    ["6784", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CLIPS P/CABO DE AÇO 1/4\"", "FERTAK", "1 un.", "0,65"],
    ["6970", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CLIPS P/CABO DE AÇO 3/8\"", "FERTAK", "1 un.", "1,55"],
    ["4035", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "COLHER DE PEDREIRO RETA 8\" C/CABO DE MADEIRA", "FERTAK", "1 un.", "8,90"],
    ["7936", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "COLHER DE PEDREIRO RETA 9\" C/CABO DE MADEIRA", "FERTAK", "1 un.", "9,60"],
    ["7761", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CONDULETE ALUMÍNIO - CAIXA MÚLTIPLA \"X\" 1/2\" - 3/4\"", "TRAMONTINA", "1 un.", "11,80"],
    ["7837", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CONDULETE ALUMÍNIO - CONECTOR UNIDUT 1\"", "TRAMONTINA", "1 un.", "3,90"],
    ["7777/7753", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CONDULETE ALUMÍNIO - CONECTOR UNIDUT 1/2\" ou 3/4\"", "TRAMONTINA", "1 un.", "3,50"],
    ["7752", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CONDULETE ALUMÍNIO - EMENDA UNIDUT 3/4\"", "TRAMONTINA", "1 un.", "4,70"],
    ["SC-0007", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CONDULETE ALUMÍNIO - PLACA 1SEÇÃO OU 2SEÇÃO OU 3SECÇÃO OU 2SEÇÃO SEP. 1/2\" - 3/4\"", "TRAMONTINA", "1 un.", "7,90"],
    ["8007/7760", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CONDULETE ALUMÍNIO - PLACA C/SUPORTE 03 MÓDULOS LIZ OU PLACA 01 TOM. VERTICAL 1/2\" - 3/4\"", "TRAMONTINA", "1 un.", "7,20"],
    ["7754", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CONDULETE ALUMÍNIO - PLACA CEGA 1/2\" - 3/4\"", "TRAMONTINA", "1 un.", "3,20"],
    ["7762", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CONDULETE ALUMÍNIO - TAMPÃO DE PVC 3/4\"", "TRAMONTINA", "1 un.", "0,30"],
    ["2161/2162", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CONDULETE PVC - CAIXA MÚLTIPLA S/TAMPA CINZA \"L\" OU \"X\"", "TRAMONTINA", "48 un.", "8,70"],
    ["2165", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CONDULETE PVC - CONECTOR P/SÁIDA DE CAIXA 1\"", "TRAMONTINA", "100 un.", "2,60"],
    ["2163", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CONDULETE PVC - CONECTOR P/SÁIDA DE CAIXA 1/2\"", "TRAMONTINA", "100 un.", "1,85"],
    ["2164/2166", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CONDULETE PVC - CONECTOR P/SÁIDA DE CAIXA 3/4\" OU EMENDA P/CAIXAS 3/4\" \" L\" OU \" X \"", "TRAMONTINA", "100 un.", "1,95"],
    ["SC-0008", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CONDULETE PVC - PLACAS 2 x 4 PVC (MOD. DIVERSOS) OU 2 x 4 C/SUP P/03 MÓD. LIZ", "TRAMONTINA", "48 un.", "4,50"],
    ["4470/7864", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CONDULETE PVC - TOMADA 3P 20A S/P C/SUPORTE PRETA OU VERMELHA", "PERLEX", "30 un.", "6,80"],
    ["6213", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CONECTOR BNC FÊMEA C/BORNE P/CÂMERA", "MXT", "1 un.", "3,40"],
    ["6685", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CONECTOR BNC JACK C/BORNE P/CÂMERA", "MXT", "1 un.", "2,10"],
    ["SC-0009", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CONECTOR BNC MACHO C/BORNE P/CÂMERA OU BNC C/MOLA ZINCO 6MM DE SOLDAR 6212/", "MXT", "1 un.", "2,60"],

    # Página 4
    ["6684/6973", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CONECTOR BNC P4 C/BORNE P/CÂMERA OU EMENDA BNC ZINCO FÊMEA x FÊMEA", "MXT", "1 un.", "1,70"],
    ["7921", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CONECTOR CABO COAXIAL RG59 C/ANEL (PACOTE C/25 PEÇAS)", "DIVERSOS", "1 un.", "12,80"],
    ["0098/4379", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CONECTOR CABO COAXIAL RG59 C/ROSCA OU RG6 C/ROSCA P/TV A CABO", "DIVERSOS", "100 un.", "0,44"],
    ["6473", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CONECTOR CABO COAXIAL RG59 EM 90º", "IMPORTADO", "1 un.", "2,10"],
    ["4423", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CONECTOR CABO COAXIAL RG59 P/CRIMPAR", "DIVERSOS", "100 un.", "0,40"],
    ["5394", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CONECTOR CABO COAXIAL RG6 C/ANEL (PACOTE C/25 PEÇAS)", "DIVERSOS", "1 un.", "13,40"],
    ["4559", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CONECTOR CABO COAXIAL RG6 DE COMPRENSSÃO LISO 3CM", "DIVERSOS", "50 un.", "3,30"],
    ["1869", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CONECTOR DE COBRE P/CABO 10,00MM", "CONIMEL", "50 un.", "7,60"],
    ["3323", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CONECTOR DE COBRE P/CABO 120,00MM", "CONIMEL", "25 un.", "33,70"],
    ["3324", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CONECTOR DE COBRE P/CABO 150,00MM", "CONIMEL", "25 un.", "44,50"],
    ["1870", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CONECTOR DE COBRE P/CABO 16,00MM", "CONIMEL", "50 un.", "9,40"],
    ["3325", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CONECTOR DE COBRE P/CABO 185,00MM", "CONIMEL", "25 un.", "57,00"],
    ["1871", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CONECTOR DE COBRE P/CABO 25,00MM", "CONIMEL", "50 un.", "12,90"],
    ["1872", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CONECTOR DE COBRE P/CABO 35,00MM", "CONIMEL", "50 un.", "14,80"],
    ["1873", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CONECTOR DE COBRE P/CABO 50,00MM", "CONIMEL", "50 un.", "17,20"],
    ["1868", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CONECTOR DE COBRE P/CABO 6,00MM", "CONIMEL", "50 un.", "7,40"],
    ["3322", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CONECTOR DE COBRE P/CABO 95,00MM", "CONIMEL", "25 un.", "29,90"],
    ["2544", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CONECTOR DE LOUÇA BIPOLAR GRANDE P/CABO ATÉ 16,00MM", "DIVERSOS", "50 un.", "3,20"],
    ["2549", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CONECTOR DE LOUÇA BIPOLAR PEQUENO P/CABO ATÉ 10,00MM", "DIVERSOS", "50 un.", "1,80"],
    ["2681", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CONECTOR DE LOUÇA TRIPOLAR GRANDE P/CABO ATÉ 16,00MM", "DIVERSOS", "50 un.", "4,60"],
    ["2682", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CONECTOR DE LOUÇA TRIPOLAR PEQUENO P/CABO ATÉ 10,00MM", "DIVERSOS", "50 un.", "2,80"],
    ["7384", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CONECTOR DERIVAÇÃO 0,50MM / 1,00MM VERMELHO", "DIVERSOS", "1 un.", "0,42"],
    ["7450", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CONECTOR GENÉRICO C/PINO ATÉ 25MM", "ENERBRÁS", "1 un.", "8,95"],
    ["7553/7028", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CONECTOR JUNÇÃO 1 POLO EMENDA 4MM - 02212411 OU CONECTOR 3 POLOS 4MM - 02210413", "WAGO", "50 un.", "3,90"],
    ["7027", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CONECTOR JUNÇÃO 2 POLOS 4MM - 02210412", "WAGO", "100 un.", "3,00"],
    ["7030", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CONECTOR JUNÇÃO 2 POLOS 6MM - 02210612", "WAGO", "50 un.", "5,70"],
    ["7031", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CONECTOR JUNÇÃO 3 POLOS 6MM - 02210613", "WAGO", "30 un.", "6,70"],
    ["7029", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CONECTOR JUNÇÃO 5 POLOS 4MM - 02210415", "WAGO", "25 un.", "6,00"],
    ["1883", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CONECTOR P/HASTE TERRA COBRE 1/2\" - 5/8\"", "CONIMEL", "50 un.", "4,20"],
    ["8129", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CONECTOR PERFURANTE MORCEGO 06MM/120MM", "CONIMEL", "1 un.", "15,80"],
    ["8011", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CONECTOR PERFURANTE MORCEGO 10MM/120MM", "DIVERSOS", "1 un.", "8,80"],
    ["8096", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CONECTOR PERFURANTE MORCEGO 10MM/150MM", "DIVERSOS", "1 un.", "11,25"],
    ["7677", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CONECTOR PERFURANTE MORCEGO 10MM/95MM", "DIVERSOS", "1 un.", "5,95"],
    ["8097", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CONECTOR PERFURANTE MORCEGO 16MM/120MM", "DIVERSOS", "1 un.", "24,40"],
    ["7924", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CONECTOR PRENSA CABO BSP IP68 C/ROSCA 3/8\"", "MARGIRIUS", "1 un.", "1,49"],
    ["3321", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CONECTOR ROSQUEÁVEL 0,50MM A 1,50MM CINZA C/50 UNDS", "DIVERSOS", "1 un.", "5,60"],
    ["3673", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CONECTOR ROSQUEÁVEL 0,50MM A 2,50MM AZUL C/50 UNDS", "DIVERSOS", "1 un.", "5,90"],

    # Página 5
    ["2106", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CONECTOR ROSQUEÁVEL 1,00MM A 4,00MM LARANJA C/50 UNDS", "DIVERSOS", "1 un.", "8,70"],
    ["3674", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CONECTOR ROSQUEÁVEL 1,00MM A 6,00MM AMARELO C/50 UNDS", "DIVERSOS", "1 un.", "11,80"],
    ["6810", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CONECTOR ROSQUEÁVEL 4,00MM A 16,00MM VERMELHO C/50 UNDS", "DIVERSOS", "1 un.", "17,40"],
    ["4378", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CONECTOR SCOTCHLOK DERIVAÇÃO 0,50MM / 1,50MM IDC558", "3M", "500 un.", "2,70"],
    ["6145", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CONECTOR SCOTCHLOK DERIVAÇÃO 1,50MM / 4,50MM IDC567", "3M", "1000 un.", "5,10"],
    ["4377", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CONECTOR SCOTCHLOK EMENDA 0,50MM / 1,50MM IDC557", "3M", "500 un.", "2,70"],
    ["1798", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CONECTOR SINDAL ( PVC ) 10,00MM BARRA C/06 PARES", "BRASFORT", "10 un.", "6,80"],
    ["1799", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CONECTOR SINDAL ( PVC ) 16,00MM BARRA C/06 PARES", "BRASFORT", "10 un.", "13,80"],
    ["6815", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CONECTOR SINDAL ( PVC ) 25,00MM BARRA C/06 PARES", "BRASFORT", "10 un.", "19,80"],
    ["1797", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CONECTOR SINDAL ( PVC ) 4,00MM BARRA C/06 PARES", "BRASFORT", "10 un.", "4,30"],
    ["1772", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CONECTOR SINDAL ( PVC ) 6,00MM BARRA C/06 PARES", "BRASFORT", "10 un.", "4,80"],
    ["6146", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CONECTOR SPLIT BOLT LATÃO P/CABO 06MM", "DIVERSOS", "1 un.", "4,90"],
    ["6147", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CONECTOR SPLIT BOLT LATÃO P/CABO 10MM", "DIVERSOS", "10 un.", "5,00"],
    ["6148", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CONECTOR SPLIT BOLT LATÃO P/CABO 16MM", "DIVERSOS", "10 un.", "6,30"],
    ["6149", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CONECTOR SPLIT BOLT LATÃO P/CABO 25MM", "DIVERSOS", "10 un.", "8,60"],
    ["6150", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CONECTOR SPLIT BOLT LATÃO P/CABO 35MM", "DIVERSOS", "10 un.", "12,80"],
    ["6625", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CONECTOR SPLIT BOLT LATÃO P/CABO 50MM", "DIVERSOS", "10 un.", "19,70"],
    ["6626", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CONECTOR SPLIT BOLT LATÃO P/CABO 70MM", "DIVERSOS", "10 un.", "21,80"],
    ["7820", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CONECTOR SPLIT BOLT LATÃO P/CABO 95MM", "DIVERSOS", "10 un.", "35,60"],
    ["6286", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CONTROLE P/ PORTÃO ELETRÔNICO PPA C/SUPORTE", "PPA", "1 un.", "26,00"],
    ["5761", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CONTROLE P/PORTÃO ELETRÔNICO MODELO TX3C PECININ C/03 BOTÕES", "PECCININ", "1 un.", "37,90"],
    ["5763", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CONTROLE P/PORTÃO ELETRÔNICO MODELO TXPRICE MC GRACIA C/03 BOTÕES", "MC GARCIA", "1 un.", "37,20"],
    ["5762", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CONTROLE P/PORTÃO ELETRÔNICO ROSSI MODELO TXHCS (ROLLING CODE)", "ROSSI", "1 un.", "45,80"],
    ["7542", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CONVERSOR/GRAVADOR DIGITAL FULL HD DTV-9000", "AQUÁRIO", "1 un.", "109,00"],
    ["8045", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CORDÃO DE LUZ MODELO TIPO VARAL 5MTS C/10 SOQUETES E27 IP65", "KIAN", "1 un.", "78,90"],
    ["2051/2052", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CORDÃO P/FERRO A VAPOR (ENCAIXE) / FERRO COMUM (FORQUILHA) 1,75MTS", "FC", "1 un.", "14,90"],
    ["6421", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CUNHA P/ABRAÇADEIRA TIPO \"D\"", "MONTEC", "50 un.", "0,20"],
    ["7010", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "DIMER / INTERRUPTOR VENTILADOR ROTATIVO EXTERNO C/TECLA", "APLACEL", "1 un.", "17,90"],
    ["7013", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "DIMER ROTATIVO DE EMBUTIR BRANCO", "APLACEL", "1 un.", "16,20"],
    ["7412", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "DIMER ROTATIVO EMBUTIR C/TECLA", "APLACEL", "1 un.", "18,40"],
    ["5475/5517", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "DISJUNTOR BIPOLAR 40A / 50A - DIN EUROPEU", "GE", "6 un.", "36,90"],
    ["7358", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "DISJUNTOR BIPOLAR 50A \"C\" PADRÃO CEMIG DIN EUROPEU", "GE", "6 un.", "48,90"],
    ["7449", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "DISJUNTOR BIPOLAR 63A \"C\" PADRÃO CEMIG DIN EUROPEU", "GE", "1 un.", "94,70"],
    ["5478", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "DISJUNTOR BIPOLAR 63A - DIN EUROPEU", "GE", "6 un.", "52,30"],
    ["SC-0014", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "DISJUNTOR BIPOLAR 16A / 20A / 25A / 32A - DIN EUROPEU", "SOPRANO", "6 un.", "28,30"],
    ["SC-0013", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "DISJUNTOR BIPOLAR 16A /20A / 25A / 32A - DIN EUROPEU", "GE", "6 un.", "34,90"],
    ["8006", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "DISJUNTOR BIPOLAR 20KA DIN DPS 275V", "SOPRANO", "1 un.", "129,80"]
]

with open('public/modelos/material_eletrico_pampulha.csv', 'a', encoding='utf-8', newline='') as f:
    writer = csv.writer(f)
    writer.writerows(rows)

print(f"Páginas 2 a 5 adicionadas: {len(rows)} itens.")
