import csv

rows = [
    # Página 17
    ["8001", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "TRANSFORMADOR TRAFO 127V/220V 1500VA", "FIOLUX", "1 un.", "219,00"],
    ["8002", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "TRANSFORMADOR TRAFO 127V/220V 2000VA", "FIOLUX", "1 un.", "289,00"],
    ["8003", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "TRANSFORMADOR TRAFO 127V/220V 3000VA", "FIOLUX", "1 un.", "398,00"],
    ["8004", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "TRANSFORMADOR TRAFO 127V/220V 5000VA", "FIOLUX", "1 un.", "619,00"],
    ["8005", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "TRANSFORMADOR TRAFO 127V/220V 7000VA", "FIOLUX", "1 un.", "890,00"],
    ["8012", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "TRENA MÉTRICA EMBORRACHADA 3 METROS x 16MM", "FERTAK", "1 un.", "7,90"],
    ["8013", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "TRENA MÉTRICA EMBORRACHADA 5 METROS x 19MM", "FERTAK", "1 un.", "12,90"],
    ["8014", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "TRENA MÉTRICA EMBORRACHADA 7,5 METROS x 25MM", "FERTAK", "1 un.", "21,50"],
    ["8015", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "TRENA MÉTRICA EMBORRACHADA 10 METROS x 25MM", "FERTAK", "1 un.", "28,70"],
    ["8016", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "TRILHO ELETRIFICADO 1 METRO BRANCO C/CONEXÃO", "DIVERSOS", "1 un.", "34,90"],
    ["8017", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "TRILHO ELETRIFICADO 1 METRO PRETO C/CONEXÃO", "DIVERSOS", "1 un.", "34,90"],
    ["8022", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "TUBO ESPIRAL CORRUGADO CONDUITE 1/2\" (ROLO 50M)", "TIGRE", "1 un.", "79,00"],
    ["8023", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "TUBO ESPIRAL CORRUGADO CONDUITE 3/4\" (ROLO 50M)", "TIGRE", "1 un.", "98,00"],
    ["8024", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "TUBO ESPIRAL CORRUGADO CONDUITE 1\" (ROLO 25M)", "TIGRE", "1 un.", "84,00"],
    ["8026", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "VALVULA DE RETENÇÃO ESGOTO 100MM", "TIGRE", "1 un.", "68,90"],
    ["8027", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "VALVULA DE RETENÇÃO ESGOTO 150MM", "TIGRE", "1 un.", "119,00"],
    ["8028", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "VARA DE MANOBRA FIBRA DE VIDRO TELESCOPICA 6M", "DIVERSOS", "1 un.", "490,00"],
    ["8029", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "VENTILADOR DE MESA 30CM 127V 6 PÁS", "VENTISILVA", "1 un.", "189,00"],
    ["8030", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "VENTILADOR DE MESA 40CM 127V 6 PÁS", "VENTISILVA", "1 un.", "229,00"],
    ["8038", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "VENTILADOR DE TETO 3 PÁS BRANCO C/LUSTRE 127V", "VENTISILVA", "1 un.", "249,00"],
    ["8039", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "VENTILADOR DE TETO 3 PÁS BRANCO C/LUSTRE 220V", "VENTISILVA", "1 un.", "249,00"],
    ["8040", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "VENTILADOR DE COLUNA 50CM PRETO OSCILANTE BIVOLT", "VENTISILVA", "1 un.", "369,00"],
    ["8041", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "VENTILADOR DE PAREDE 50CM PRETO OSCILANTE BIVOLT", "VENTISILVA", "1 un.", "349,00"],
    ["8042", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "VENTILADOR DE PAREDE 65CM PRETO OSCILANTE BIVOLT", "VENTISILVA", "1 un.", "419,00"],
    ["8043", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "VERGALHÃO DE FERRO 3/8\" BARRA 12M", "GERDAU", "1 un.", "48,50"],
    ["8044", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "VERGALHÃO DE FERRO 5/16\" BARRA 12M", "GERDAU", "1 un.", "34,20"],
    ["8046", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "VIDRO PROTEÇÃO P/MASCARA DE SOLDA 108 x 51MM INCOLOR", "DIVERSOS", "1 un.", "1,20"],
    ["8047", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "VIDRO PROTEÇÃO P/MASCARA DE SOLDA 108 x 51MM ESCURO 10/12", "DIVERSOS", "1 un.", "1,80"],
    ["8065", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CABO DE COBRE NU 16MM", "CONDUMIG", "1 mt.", "12,90"],
    ["8066", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CABO DE COBRE NU 25MM", "CONDUMIG", "1 mt.", "19,50"],
    ["8067", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CABO DE COBRE NU 35MM", "CONDUMIG", "1 mt.", "27,80"],
    ["8068", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CABO DE COBRE NU 50MM", "CONDUMIG", "1 mt.", "39,40"],
    ["8069", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CABO DE COBRE NU 70MM", "CONDUMIG", "1 mt.", "56,90"],
    ["8070", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CABO FLEXÍVEL SIL 1,50MM 750V (ROLO 100M)", "SIL", "1 un.", "139,00"],
    ["8071", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CABO FLEXÍVEL SIL 2,50MM 750V (ROLO 100M)", "SIL", "1 un.", "219,00"],
    ["8072", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CABO FLEXÍVEL SIL 4,00MM 750V (ROLO 100M)", "SIL", "1 un.", "349,00"],
    ["8073", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CABO FLEXÍVEL SIL 6,00MM 750V (ROLO 100M)", "SIL", "1 un.", "519,00"],

    # Página 18
    ["8074", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CABO FLEXÍVEL SIL 10,00MM 750V (ROLO 100M)", "SIL", "1 un.", "890,00"],
    ["8075", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CABO FLEXÍVEL SIL 16,00MM 750V (ROLO 100M)", "SIL", "1 un.", "1450,00"],
    ["8076", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CABO PARALELO 2x0,75MM 300V (ROLO 100M)", "CONDUMIG", "1 un.", "98,00"],
    ["8077", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CABO PARALELO 2x1,50MM 300V (ROLO 100M)", "CONDUMIG", "1 un.", "189,00"],
    ["8078", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CABO PARALELO 2x2,50MM 300V (ROLO 100M)", "CONDUMIG", "1 un.", "299,00"],
    ["8079", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CABO PP 2x1,50MM 500V (ROLO 100M)", "SIL", "1 un.", "329,00"],
    ["8080", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CABO PP 2x2,50MM 500V (ROLO 100M)", "SIL", "1 un.", "498,00"],
    ["8081", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CABO PP 3x1,50MM 500V (ROLO 100M)", "SIL", "1 un.", "449,00"],
    ["8082", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CABO PP 3x2,50MM 500V (ROLO 100M)", "SIL", "1 un.", "698,00"],
    ["8083", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CABO PP 4x1,50MM 500V (ROLO 100M)", "SIL", "1 un.", "598,00"],
    ["8084", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CABO PP 4x2,50MM 500V (ROLO 100M)", "SIL", "1 un.", "890,00"],
    ["8085", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CABO REDE COAXIAL RG59 75 OHMS 67% (ROLO 100M)", "MEGATRON", "1 un.", "119,00"],
    ["8086", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CABO REDE COAXIAL RG6 75 OHMS 60% (ROLO 100M)", "MEGATRON", "1 un.", "149,00"],
    ["8087", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CABO REDE DE DADOS UTP 4 PARES CAT5E (CAIXA 305M) AZUL", "FURUKAWA", "1 un.", "490,00"],
    ["8088", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CABO REDE DE DADOS UTP 4 PARES CAT6 (CAIXA 305M) AZUL", "FURUKAWA", "1 un.", "790,00"],
    ["8089", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CABO TELEFÔNICO CCI 2 PARES (ROLO 100M)", "MEGATRON", "1 un.", "89,00"],
    ["8090", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CABO TELEFÔNICO CCI 3 PARES (ROLO 100M)", "MEGATRON", "1 un.", "129,00"],
    ["8092", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CAIXA DE INSPEÇÃO P/ATERRAMENTO PVC C/TAMPA", "TAF", "1 un.", "24,80"],
    ["8093", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CAIXA DE MEDIÇÃO MONOFÁSICA CEMIG CM-1 POLICARBONATO", "TAF", "1 un.", "139,00"],
    ["8094", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CAIXA DE MEDIÇÃO POLIFÁSICA CEMIG CM-2 POLICARBONATO", "TAF", "1 un.", "229,00"],
    ["8095", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CAIXA SIFONADA PVC 100x100x50 GRELHA BRANCA", "TIGRE", "1 un.", "18,90"],
    ["8098", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CAIXA SIFONADA PVC 150x150x50 GRELHA INOX", "TIGRE", "1 un.", "42,80"],
    ["8100", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CALHA SOBREPOR CHAPA SLIM 2x18W 120CM BRANCA", "DIVERSOS", "1 un.", "34,80"],
    ["8101", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CHAVE TESTE COMUM PONTINHA FENDA", "FERTAK", "1 un.", "2,90"],
    ["8102", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "CORTADOR DE TUBOS PVC ATÉ 42MM", "FERTAK", "1 un.", "39,00"],
    ["8103", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "DISCO DE CORTE FINO INOX 4.1/2\" x 1,0MM", "NORTON", "10 un.", "3,90"],
    ["8104", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "DISCO DE DESBASTE FERRO 4.1/2\" x 6,0MM", "NORTON", "5 un.", "8,90"],
    ["8105", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "DISCO DIAMANTADO SEGMENTADO 110MM CONCRETO", "NORTON", "1 un.", "19,80"],
    ["8107", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "DISCO DIAMANTADO TURBO 110MM PISO/PORCELANATO", "NORTON", "1 un.", "22,50"],
    ["8108", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "ENGATE FLEXÍVEL INOX 1/2\" x 40CM P/LAVATÓRIO", "BLUKIT", "1 un.", "16,90"],
    ["8109", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "ENGATE FLEXÍVEL INOX 1/2\" x 60CM P/LAVATÓRIO", "BLUKIT", "1 un.", "21,50"],
    ["8110", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "ESPELHO 4x2 CEGO BRANCO", "PERLEX", "20 un.", "1,90"],
    ["8111", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "ESPELHO 4x4 CEGO BRANCO", "PERLEX", "10 un.", "3,80"],
    ["8113", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "FITA VEDA ROSCA 18MM x 10M", "TIGRE", "10 un.", "2,90"],
    ["8114", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "FITA VEDA ROSCA 18MM x 25M", "TIGRE", "10 un.", "6,40"],
    ["8115", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "FITA VEDA ROSCA 18MM x 50M", "TIGRE", "10 un.", "11,80"],
    ["8116", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "GRAMPADOR MANUAL TIPO TAPECEIRO AÇO", "FERTAK", "1 un.", "49,90"],

    # Página 19
    ["8117", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "GRAMPO P/GRAMPADOR TAPECEIRO 106/8MM (CX 5000)", "FERTAK", "1 un.", "14,80"],
    ["8120", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "JOELHO ESGOTO 90º 100MM", "TIGRE", "1 un.", "4,90"],
    ["8122", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "JOELHO ESGOTO 90º 50MM", "TIGRE", "1 un.", "2,80"],
    ["8123", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "JOELHO ESGOTO 90º 40MM", "TIGRE", "1 un.", "1,95"],
    ["8124", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "JOELHO SOLDÁVEL 90º 25MM ÁGUA FRIA", "TIGRE", "1 un.", "1,10"],
    ["8125", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "JOELHO SOLDÁVEL 90º 32MM ÁGUA FRIA", "TIGRE", "1 un.", "2,30"],
    ["8126", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "JOELHO SOLDÁVEL C/BUCHA LATÃO 25 x 1/2\" 90º", "TIGRE", "1 un.", "5,40"],
    ["8127", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "JOELHO SOLDÁVEL C/BUCHA LATÃO 25 x 3/4\" 90º", "TIGRE", "1 un.", "6,20"],
    ["8128", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "LÂMPADA VAPOR METÁLICO TUBULAR 400W E-40", "OSRAM", "1 un.", "69,00"],
    ["8130", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "LÂMPADA VAPOR METÁLICO TUBULAR 250W E-40", "OSRAM", "1 un.", "59,00"],
    ["8131", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "LUVA ESGOTO 100MM", "TIGRE", "1 un.", "4,80"],
    ["8132", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "LUVA ESGOTO 50MM", "TIGRE", "1 un.", "2,60"],
    ["8133", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "LUVA ESGOTO 40MM", "TIGRE", "1 un.", "1,80"],
    ["8134", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "LUVA SOLDÁVEL 25MM ÁGUA FRIA", "TIGRE", "1 un.", "0,95"],
    ["8135", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "LUVA SOLDÁVEL 32MM ÁGUA FRIA", "TIGRE", "1 un.", "1,90"],
    ["8136", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "NÍVEL DE ALUMÍNIO 3 BOLHAS 12\" (30CM)", "FERTAK", "1 un.", "16,90"],
    ["8138", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "NÍVEL DE ALUMÍNIO 3 BOLHAS 20\" (50CM)", "FERTAK", "1 un.", "24,80"],
    ["8139", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "PASTA P/SOLDAR ESTANHO 110G", "COBIX", "1 un.", "14,50"],
    ["8140", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "PISTOLA DE COLA QUENTE BIVOLT 40W GROSSA", "FERTAK", "1 un.", "26,90"],
    ["8142", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "REFIL COLA QUENTE GROSSO 11MM (PACOTE 1KG)", "DIVERSOS", "1 un.", "42,00"],
    ["8143", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "REGISTRO DE ESFERA PVC SOLDÁVEL 25MM", "TIGRE", "1 un.", "14,90"],
    ["8144", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "REGISTRO DE ESFERA PVC SOLDÁVEL 32MM", "TIGRE", "1 un.", "22,80"],
    ["8145", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "REGISTRO DE ESFERA PVC SOLDÁVEL 50MM", "TIGRE", "1 un.", "46,00"],
    ["8146", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "REGISTRO DE GAVETA BRUTO LATÃO 3/4\"", "DECA", "1 un.", "49,90"],
    ["8147", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "REGISTRO DE GAVETA BRUTO LATÃO 1\"", "DECA", "1 un.", "69,00"],
    ["8148", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "REGISTRO DE PRESSÃO BRUTO LATÃO 1/2\"", "DECA", "1 un.", "44,50"],
    ["8149", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "REGISTRO DE PRESSÃO BRUTO LATÃO 3/4\"", "DECA", "1 un.", "49,00"],
    ["8150", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "SERRA COPO JOGO P/MADEIRA/PVC 8 PEÇAS", "FERTAK", "1 un.", "38,90"],
    ["8151", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "SIFÃO SANFONADO UNIVERSAL BRANCO 72CM", "BLUKIT", "1 un.", "8,90"],
    ["8152", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "SIFÃO SANFONADO DUPLO BRANCO UNIVERSAL", "BLUKIT", "1 un.", "18,90"],
    ["8153", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "SOLDADOR ELÉTRICO TIPO MACHADINHA 100W 127V", "HIKARI", "1 un.", "68,00"],
    ["8154", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "SOLDADOR ELÉTRICO TIPO MACHADINHA 150W 127V", "HIKARI", "1 un.", "89,00"],
    ["8155", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "SUPORTE P/CONDUÍTE 3/4\" TIPO ORELHA (PACOTE C/50)", "DIVERSOS", "1 un.", "14,50"],
    ["8156", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "SUPORTE P/CONDUÍTE 1/2\" TIPO ORELHA (PACOTE C/50)", "DIVERSOS", "1 un.", "12,90"],
    ["8157", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "TÊ ESGOTO 100MM", "TIGRE", "1 un.", "8,90"],
    ["8158", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "TÊ ESGOTO 50MM", "TIGRE", "1 un.", "4,80"],
    ["8159", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "TÊ SOLDÁVEL 25MM ÁGUA FRIA", "TIGRE", "1 un.", "1,60"],

    # Página 20
    ["8160", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "TÊ SOLDÁVEL 32MM ÁGUA FRIA", "TIGRE", "1 un.", "3,20"],
    ["8161", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "TÊ SOLDÁVEL C/BUCHA LATÃO 25 x 1/2\" REDUÇÃO", "TIGRE", "1 un.", "7,90"],
    ["8162", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "TORNEIRA BÓIA CAIXA D'ÁGUA 1/2\" E 3/4\"", "TIGRE", "1 un.", "24,80"],
    ["8163", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "TORNEIRA DE ESFERA P/JARDIM E MÁQUINA DE LAVAR 1/2\" x 3/4\"", "DIVERSOS", "1 un.", "21,90"],
    ["8164", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "TORNEIRA PLÁSTICA JARDIM 3/4\" BRANCA", "HERC", "1 un.", "4,90"],
    ["8167", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "TUBO ESGOTO 100MM BARRA 6 METROS", "TIGRE", "1 un.", "59,00"],
    ["8168", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "TUBO ESGOTO 50MM BARRA 6 METROS", "TIGRE", "1 un.", "38,00"],
    ["8169", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "TUBO SOLDÁVEL 25MM ÁGUA FRIA BARRA 6 METROS", "TIGRE", "1 un.", "28,00"],
    ["8170", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "TUBO SOLDÁVEL 32MM ÁGUA FRIA BARRA 6 METROS", "TIGRE", "1 un.", "49,00"],
    ["8171", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "VALVULA DE ESCOAMENTO P/LAVATÓRIO 1\" PLÁSTICA BRANCA", "BLUKIT", "1 un.", "8,90"],
    ["8172", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "VALVULA DE ESCOAMENTO P/PIA AMERICANA 3.1/2\" INOX", "BLUKIT", "1 un.", "24,90"],
    ["8173", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "VALVULA DE ESCOAMENTO P/TANQUE 1.1/4\" PLÁSTICA BRANCA", "BLUKIT", "1 un.", "11,50"],
    ["8174", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "VASO SANITÁRIO CONVENCIONAL BRANCO", "CELITE", "1 un.", "149,00"],
    ["8175", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "VEDANTE P/TORNEIRA 1/2\" BORRACHA (PACOTE C/10)", "DIVERSOS", "1 un.", "3,50"],
    ["8176", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "VENTILADOR OSCILANTE DE PAREDE 60CM BIVOLT", "TRON", "1 un.", "299,00"],
    ["8177", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "VENTILADOR OSCILANTE DE COLUNA 60CM BIVOLT", "TRON", "1 un.", "329,00"],
    ["8178", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "SIFÃO SANFONADO COPO CROMADO UNIVERSAL", "BLUKIT", "1 un.", "39,00"],
    ["8179", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "ENGATE FLEXÍVEL PLÁSTICO TRANÇADO 1/2\" x 40CM", "HERC", "1 un.", "7,90"],
    ["8180", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "ENGATE FLEXÍVEL PLÁSTICO TRANÇADO 1/2\" x 50CM", "HERC", "1 un.", "8,90"],
    ["8181", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "TAMPA DE CAIXA DE GORDURA REFORÇADA PVC", "TIGRE", "1 un.", "49,00"],
    ["8182", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "GRELHA ROTATIVA INOX 10 x 10CM REDONDA", "DIVERSOS", "1 un.", "12,50"],
    ["8183", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "GRELHA ROTATIVA INOX 15 x 15CM REDONDA", "DIVERSOS", "1 un.", "18,90"],
    ["8184", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "PORTA GRELHA QUADRADO PVC 10 x 10CM BRANCO", "TIGRE", "1 un.", "4,50"],
    ["8185", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "PORTA GRELHA QUADRADO PVC 15 x 15CM BRANCO", "TIGRE", "1 un.", "7,90"],
    ["8186", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "ANEL DE VEDAÇÃO P/VASO SANITÁRIO C/GUIA", "BLUKIT", "1 un.", "14,80"],
    ["8187", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "PARAFUSO P/VASO SANITÁRIO LATONADO B-10 (PAR)", "DIVERSOS", "1 un.", "12,90"],
    ["8188", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "PARAFUSO P/VASO SANITÁRIO INOX B-10 (PAR)", "DIVERSOS", "1 un.", "19,80"],
    ["8189", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "ASSENTO SANITÁRIO OVAL UNIVERSAL BRANCO POLIÉSTER", "ASTRA", "1 un.", "39,90"],
    ["8190", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "ASSENTO SANITÁRIO ALMOFADADO BRANCO OVAL", "ASTRA", "1 un.", "59,00"],
    ["8191", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "TUBO DE LIGAÇÃO SANITÁRIO AJUSTÁVEL C/ESPELHO", "BLUKIT", "1 un.", "16,80"],
    ["8192", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "BOLSA DE LIGAÇÃO P/VASO SANITÁRIO PRETA OU BRANCA", "BLUKIT", "1 un.", "4,50"],
    ["8193", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "ADESIVO PLÁSTICO P/PVC BISNAGA 75G", "TIGRE", "1 un.", "7,90"],
    ["8194", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "ADESIVO PLÁSTICO P/PVC FRASCO C/PINCEL 175G", "TIGRE", "1 un.", "19,80"],
    ["8195", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "SOLUÇÃO LIMPADORA PREPARADORA P/PVC FRASCO 200ML", "TIGRE", "1 un.", "18,90"],
    ["8196", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "GRAXA BRANCA ESPECIAL EM TUBO 80G", "DIVERSOS", "1 un.", "9,80"]
]

with open('public/modelos/material_eletrico_pampulha.csv', 'a', encoding='utf-8', newline='') as f:
    writer = csv.writer(f)
    writer.writerows(rows)

print(f"Páginas 17 a 20 adicionadas: {len(rows)} itens.")
