import csv

rows = [
    # Página 13
    ["7370", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "PINO ADAPTADOR 2P BRANCO", "PERLEX", "10 un.", "3,95"],
    ["7080", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "PINO ADAPTADOR 2P BRANCO C/SAÍDA BORRACHA", "DIVERSOS", "1 un.", "3,50"],
    ["4537/4538", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "PINO ADAPTADOR ANTIGO 2P P/NOVO 3P 10A / 20A BRANCO", "PERLEX", "10 un.", "3,95"],
    ["7552", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "PINO ADAPTADOR NOVO 3P 20A P/NOVO 3P 10A BRANCO", "PERLEX", "10 un.", "6,40"],
    ["4539/4540", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "PINO ADAPTADOR NOVO 3P P/ANTIGO 2P 10A / 20A BRANCO", "PERLEX", "10 un.", "3,95"],
    ["7585", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "PINO ADAPTADOR REVERSO 20A P/10A BRANCO", "DIVERSOS", "1 un.", "3,90"],
    ["6168", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "PINO CRUZETA 4 SAÍDAS NOVO PADRÃO 10A BRANCO", "DIVERSOS", "1 un.", "4,20"],
    ["2114", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "PINO DE ENGATE RÁPIDO P/CABO DE SOLDA 10/25MM", "DIVERSOS", "1 un.", "18,90"],
    ["7269", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "PINO FÊMEA 2P+T 10A NOVO PADRÃO PRETO", "F. C.", "10 un.", "5,20"],
    ["7270", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "PINO FÊMEA 2P+T 20A NOVO PADRÃO PRETO", "F. C.", "10 un.", "5,70"],
    ["2124", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "PINO FÊMEA PRETO 2P 10A", "PERLEX", "25 un.", "3,90"],
    ["3865", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "PINO GUIA P/PUXAR FIO 15MTS DE NYLON S/AÇO", "DIVERSOS", "1 un.", "11,80"],
    ["3866", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "PINO GUIA P/PUXAR FIO 20MTS DE NYLON S/AÇO", "DIVERSOS", "1 un.", "14,90"],
    ["6290", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "PINO MACHO 2 PÓLOS 10A PRETO", "F. C.", "10 un.", "1,90"],
    ["7267", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "PINO MACHO 2P+T 10A NOVO PADRÃO PRETO", "F. C.", "10 un.", "4,60"],
    ["7268", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "PINO MACHO 2P+T 20A NOVO PADRÃO PRETO", "F. C.", "10 un.", "4,80"],
    ["4505", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "PINO MACHO 3 PÓLOS 10A 90º PRETO", "PERLEX", "25 un.", "4,80"],
    ["4506", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "PINO MACHO 3 PÓLOS 20A 90º PRETO", "PERLEX", "25 un.", "5,95"],
    ["2123", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "PINO MACHO PRETO 2P 10A", "PERLEX", "25 un.", "3,50"],
    ["7368", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "PINO MULTIPLICADOR 3 SAÍDAS 10A PRETO", "PERLEX", "10 un.", "6,40"],
    ["7081", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "PINO T 3 SAIDAS NOVO PADRAO 10A BRANCO C/SAÍDA BORRACHA", "DIVERSOS", "1 un.", "4,95"],
    ["4508", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "PINO \"T\" 3 SAÍDAS NOVO PADRÃO 10A BRANCO", "PERLEX", "10 un.", "6,50"],
    ["4507", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "PINO \"T\" 3 SAÍDAS NOVO PADRÃO 20A BRANCO", "PERLEX", "10 un.", "7,90"],
    ["7780", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "PISTOLA DE SILICONE CHAPA TIPO ESQUELETO", "FERTAK", "1 un.", "13,90"],
    ["7104/7106", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "PLAFON LED RED. SOBREPOR 18W 6500K LUZ FRIA / 18W 3000K LUZ QUENTE 1.332LM", "DIVERSOS", "1 un.", "18,90"],
    ["7107", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "PLAFON LED RED. SOBREPOR 24W 6500K LUZ FRIA 1.776LM", "DIVERSOS", "1 un.", "24,80"],
    ["7105/7440", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "PLAFON LED REDONDO EMBUTIR 18W 6500K LUZ FRIA / 18W 3000K LUZ QUENTE 1.332 LM", "DIVERSOS", "1 un.", "15,50"],
    ["7109", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "PLAFON LED REDONDO EMBUTIR 24W 6500K LUZ FRIA 1.776 LM", "DIVERSOS", "1 un.", "19,90"],
    ["8025", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "PLAFON LED SOBREPOR QUADRADO 12W BIVOLT 6.500K 900LM", "DIVERSOS", "1 un.", "14,90"],
    ["7101", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "PLAFON LED SOBREPOR QUADRADO 18W 6.500K LUZ FRIA 1.332 LM", "DIVERSOS", "1 un.", "18,90"],
    ["7102", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "PLAFON LED SOBREPOR QUADRADO 24W 6.500K LUZ FRIA 1.776 LM", "DIVERSOS", "1 un.", "24,80"],
    ["7103", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "PLAFON LED SOBREPOR QUADRADO 36W 6.500K LUZ FRIA 3.420 LM", "DIVERSOS", "1 un.", "79,80"],
    ["7723", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "PLAFON PVC BRANCO C/SOQUETE DE LOUÇA E-27", "TAF", "50 un.", "3,80"],
    ["6923", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "PLAFONIER PVC BRANCO C/SOQUETE DE LOUÇA E-27", "PLASTIFACIL", "10 un.", "4,20"],
    ["6379", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "PLUG P2 STEREO C/MOLA METAL", "DIVERSOS", "1 un.", "2,70"],
    ["7438", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "PONTEIRO C/PROTETOR DE BORRACHA 12\"", "FERTAK", "1 un.", "18,50"],
    ["7437", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "PONTEIRO OITAVADO S/PROTETOR 10\"", "FERTAK", "1 un.", "11,50"],

    # Página 14
    ["7436", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "PONTEIRO OITAVADO S/PROTETOR 12\"", "FERTAK", "1 un.", "12,90"],
    ["6936", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "PORTA ELETRODO 500A TIPO CANETA", "FERTAK", "1 un.", "37,60"],
    ["171", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "PREGO DE AÇO C/CABEÇA 18 x 27 ( C/100UNDS )", "DIVERSOS", "1 un.", "14,80"],
    ["169", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "PREGO DE AÇO C/CABEÇA 18 x 30 ( C/100UNDS )", "DIVERSOS", "1 un.", "18,20"],
    ["170", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "PREGO DE AÇO S/CABEÇA 18 x 27 ( C/100UNDS )", "DIVERSOS", "1 un.", "14,80"],
    ["7928", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "PROLONGADOR P/CAIXA DE LUZ 4x2 PVC AMARELO", "PLASTIBRAS", "1 un.", "1,20"],
    ["7929", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "PROLONGADOR P/CAIXA DE LUZ 4x4 PVC AMARELO", "PLASTIBRAS", "1 un.", "2,10"],
    ["7374", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "PROTETOR RAIO ELETRÔNICO P/ELETRODOMÉSTICO 127V", "PW", "1 un.", "24,80"],
    ["7375", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "PROTETOR RAIO ELETRÔNICO P/ELETRODOMÉSTICO 220V", "PW", "1 un.", "26,90"],
    ["7832", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "QUADRO DE COMANDO SOBREPOR METAL 30 x 20 x 20", "BRUM", "1 un.", "149,00"],
    ["7833", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "QUADRO DE COMANDO SOBREPOR METAL 40 x 30 x 20", "BRUM", "1 un.", "198,00"],
    ["7834", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "QUADRO DE COMANDO SOBREPOR METAL 50 x 40 x 20", "BRUM", "1 un.", "285,00"],
    ["7835", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "QUADRO DE COMANDO SOBREPOR METAL 60 x 50 x 20", "BRUM", "1 un.", "419,00"],
    ["7836", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "QUADRO DE COMANDO SOBREPOR METAL 80 x 60 x 20", "BRUM", "1 un.", "569,00"],
    ["7914", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "QUADRO DISTRIBUIÇÃO EMBUTIR 04 DIN BRANCO S/BARRAMENTO", "TIGRE", "1 un.", "46,80"],
    ["7915", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "QUADRO DISTRIBUIÇÃO EMBUTIR 08 DIN BRANCO S/BARRAMENTO", "TIGRE", "1 un.", "63,20"],
    ["7916", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "QUADRO DISTRIBUIÇÃO EMBUTIR 12 DIN BRANCO S/BARRAMENTO", "TIGRE", "1 un.", "76,80"],
    ["7917", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "QUADRO DISTRIBUIÇÃO EMBUTIR 18 DIN BRANCO S/BARRAMENTO", "TIGRE", "1 un.", "119,00"],
    ["7918", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "QUADRO DISTRIBUIÇÃO EMBUTIR 24 DIN BRANCO S/BARRAMENTO", "TIGRE", "1 un.", "149,00"],
    ["7920", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "QUADRO DISTRIBUIÇÃO EMBUTIR 36 DIN BRANCO S/BARRAMENTO", "TIGRE", "1 un.", "219,00"],
    ["8056", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "QUADRO DISTRIBUIÇÃO EMBUTIR PVC 04 DIN OPACA", "PLASTIMAX", "1 un.", "23,90"],
    ["8057", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "QUADRO DISTRIBUIÇÃO EMBUTIR PVC 08 DIN OPACA", "PLASTIMAX", "1 un.", "32,90"],
    ["8058", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "QUADRO DISTRIBUIÇÃO EMBUTIR PVC 12 DIN OPACA", "PLASTIMAX", "1 un.", "42,90"],
    ["8059", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "QUADRO DISTRIBUIÇÃO EMBUTIR PVC 18 DIN OPACA", "PLASTIMAX", "1 un.", "63,20"],
    ["8060", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "QUADRO DISTRIBUIÇÃO EMBUTIR PVC 24 DIN OPACA", "PLASTIMAX", "1 un.", "83,90"],
    ["8061", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "QUADRO DISTRIBUIÇÃO EMBUTIR PVC 36 DIN OPACA", "PLASTIMAX", "1 un.", "119,80"],
    ["8052", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "QUADRO DISTRIBUIÇÃO SOBREPOR PVC 04 DIN OPACA", "PLASTIMAX", "1 un.", "24,80"],
    ["8053", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "QUADRO DISTRIBUIÇÃO SOBREPOR PVC 08 DIN OPACA", "PLASTIMAX", "1 un.", "33,80"],
    ["8054", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "QUADRO DISTRIBUIÇÃO SOBREPOR PVC 12 DIN OPACA", "PLASTIMAX", "1 un.", "44,90"],
    ["8055", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "QUADRO DISTRIBUIÇÃO SOBREPOR PVC 18 DIN OPACA", "PLASTIMAX", "1 un.", "65,80"],
    ["7446", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "RECEPTÁCULO COMUM FIXO TETO/PAREDE C/RABICHO PRETO E-27", "DIVERSOS", "12 un.", "2,20"],
    ["6926", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "RECEPTÁCULO COMUM FIXO TETO/PAREDE PRETO E-27", "DIVERSOS", "12 un.", "1,90"],
    ["7923", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "RECEPTÁCULO DE ENCAIXE P/LÂMPADA HALOPIN G9", "IMPORTADO", "1 un.", "4,90"],
    ["3607", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "RECEPTÁCULO DE LOUÇA FIXO TETO/PAREDE E-27 C/SUPORTE", "DIVERSOS", "20 un.", "3,80"],
    ["6976", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "RECEPTÁCULO DE LOUÇA FIXO TETO/PAREDE E-40 C/SUPORTE", "DIVERSOS", "1 un.", "14,50"],
    ["3608", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "RECEPTÁCULO DE LOUÇA SUSPENSO E-27", "DIVERSOS", "20 un.", "3,40"],
    ["3609", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "RECEPTÁCULO DE LOUÇA SUSPENSO E-40", "DIVERSOS", "1 un.", "12,90"],

    # Página 15
    ["6927", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "RECEPTÁCULO DE PLÁSTICO C/CHAVE CORRENTE E-27", "DIVERSOS", "1 un.", "16,80"],
    ["6928", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "RECEPTÁCULO DE PORCELANA C/CHAVE CORRENTE E-27", "DIVERSOS", "1 un.", "21,50"],
    ["6924", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "RECEPTÁCULO P/LÂMPADA FLUORESCENTE TUBOLAR G-13", "DIVERSOS", "24 un.", "1,90"],
    ["6925", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "RECEPTÁCULO P/LÂMPADA FLUORESCENTE TUBOLAR G-13 ROTATIVO", "DIVERSOS", "24 un.", "2,30"],
    ["6743", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "REFLETOR LED 100W BIVOLT 6.500K LUZ FRIA SLIM", "DIVERSOS", "1 un.", "39,80"],
    ["6742", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "REFLETOR LED 50W BIVOLT 6.500K LUZ FRIA SLIM", "DIVERSOS", "1 un.", "26,90"],
    ["7829", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "REGULADOR DE TENSÃO MONOFÁSICO 1.000VA 127V", "FIOLUX", "1 un.", "198,00"],
    ["7830", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "REGULADOR DE TENSÃO MONOFÁSICO 1.500VA 127V", "FIOLUX", "1 un.", "239,00"],
    ["7831", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "REGULADOR DE TENSÃO MONOFÁSICO 2.000VA 127V", "FIOLUX", "1 un.", "299,00"],
    ["3692", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "RELÉ FOTOELÉTRICO ELETRÔNICO BIVOLT C/BASE", "EXATRON", "1 un.", "28,70"],
    ["3691", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "RELÉ FOTOELÉTRICO ELETRÔNICO BIVOLT S/BASE", "EXATRON", "1 un.", "19,80"],
    ["3693", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "RELÉ FOTOELÉTRICO MAGNÉTICO BIVOLT S/BASE", "EXATRON", "1 un.", "22,50"],
    ["7441", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "RESISTÊNCIA DUCHA BELLA DUCHA / FASHION 127V 5.500W", "LORENZETTI", "1 un.", "15,80"],
    ["7442", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "RESISTÊNCIA DUCHA BELLA DUCHA / FASHION 220V 6.800W", "LORENZETTI", "1 un.", "15,80"],
    ["6988", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "RESISTÊNCIA DUCHA DUCHA ADVANCED / TOP JET 127V 5.500W", "LORENZETTI", "1 un.", "21,50"],
    ["6989", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "RESISTÊNCIA DUCHA DUCHA ADVANCED / TOP JET 220V 7.500W", "LORENZETTI", "1 un.", "21,50"],
    ["6984", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "RESISTÊNCIA DUCHA LOREN SHOWER 127V 5.500W", "LORENZETTI", "1 un.", "18,90"],
    ["6985", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "RESISTÊNCIA DUCHA LOREN SHOWER 220V 7.500W", "LORENZETTI", "1 un.", "18,90"],
    ["6986", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "RESISTÊNCIA DUCHA MAXI DUCHA / BELLO BANHO 127V 5.500W", "LORENZETTI", "1 un.", "12,90"],
    ["6987", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "RESISTÊNCIA DUCHA MAXI DUCHA / BELLO BANHO 220V 5.500W", "LORENZETTI", "1 un.", "12,90"],
    ["8018", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "ROLO DE LÃ S/RESPINGO 23CM C/CABO", "ATLAS", "1 un.", "22,80"],
    ["8019", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "ROLO DE LÃ S/RESPINGO 23CM S/CABO (REFIL)", "ATLAS", "1 un.", "15,90"],
    ["8020", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "ROLO DE LÃ S/RESPINGO 9CM C/CABO", "ATLAS", "1 un.", "11,80"],
    ["8021", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "ROLO DE LÃ S/RESPINGO 9CM S/CABO (REFIL)", "ATLAS", "1 un.", "7,20"],
    ["7925", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "ROTEADOR WIRELESS 300MBPS 02 ANTENAS TL-WR840N", "TP-LINK", "1 un.", "129,00"],
    ["7926", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "ROTEADOR WIRELESS 300MBPS 03 ANTENAS TL-WR845N", "TP-LINK", "1 un.", "159,00"],
    ["7927", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "ROTEADOR WIRELESS DUAL BAND AC1200 04 ANTENAS ARCHER C54", "TP-LINK", "1 un.", "219,00"],
    ["7733", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "SENSOR DE PRESENÇA ARTICULADO DE PAREDE/TETO BIVOLT", "EXATRON", "1 un.", "36,80"],
    ["7734", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "SENSOR DE PRESENÇA DE EMBUTIR 4x2 BIVOLT", "EXATRON", "1 un.", "41,90"],
    ["7735", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "SENSOR DE PRESENÇA DE SOBREPOR TETO 360º BIVOLT", "EXATRON", "1 un.", "37,90"],
    ["7736", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "SENSOR DE PRESENÇA P/SOQUETE E-27 BIVOLT", "EXATRON", "1 un.", "39,90"],
    ["7781", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "SILICONE ACÉTICO TRANSPARENTE 280G", "TEKBOND", "1 un.", "17,90"],
    ["7783", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "SILICONE PU 40 CINZA OU PRETO 400G", "TEKBOND", "1 un.", "23,90"],
    ["7855", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "SOQUETE DE BORRACHA C/RABICHO PRETO E-27", "DIVERSOS", "20 un.", "2,60"],
    ["7856", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "SOQUETE GU10 P/LÂMPADA DICRÓICA C/RABICHO", "DIVERSOS", "20 un.", "3,20"],
    ["7857", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "SPOT EMBUTIR DIRECIONÁVEL REDONDO P/DICRÓICA GU10 BRANCO", "DIVERSOS", "1 un.", "8,90"],
    ["7858", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "SPOT EMBUTIR DIRECIONÁVEL QUADRADO P/DICRÓICA GU10 BRANCO", "DIVERSOS", "1 un.", "9,50"],

    # Página 16
    ["7859", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "SPOT SOBREPOR DIRECIONÁVEL 1 LÂMPADA E-27 BRANCO OU PRETO", "DIVERSOS", "1 un.", "18,90"],
    ["7860", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "SPOT SOBREPOR DIRECIONÁVEL 2 LÂMPADAS E-27 BRANCO OU PRETO", "DIVERSOS", "1 un.", "34,80"],
    ["7861", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "SPOT SOBREPOR DIRECIONÁVEL 3 LÂMPADAS E-27 BRANCO OU PRETO", "DIVERSOS", "1 un.", "49,90"],
    ["7930", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "SUPORTE ARTICULADO P/TV 10\" A 55\"", "FERTAK", "1 un.", "48,90"],
    ["7931", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "SUPORTE FIXO P/TV 14\" A 84\"", "FERTAK", "1 un.", "19,80"],
    ["7932", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "SUPORTE P/ROLO DE PINTURA 23CM", "ATLAS", "1 un.", "9,80"],
    ["7933", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "SUPORTE UNIVERSAL P/MICRO-ONDAS BRANCO", "FERTAK", "1 un.", "39,90"],
    ["7963", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "TAMPA CEGA 3x3 PVC REDONDA BRANCA", "PLASTIBRAS", "50 un.", "1,20"],
    ["7964", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "TAMPA CEGA 4x2 PVC RETANGULAR BRANCA", "PLASTIBRAS", "50 un.", "1,40"],
    ["7965", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "TAMPA CEGA 4x4 PVC QUADRADA BRANCA", "PLASTIBRAS", "25 un.", "2,30"],
    ["7966", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "TERMINAL COMPRESSÃO ILHÓS TUBOLAR 0,75MM (PACOTE C/100UNDS)", "DIVERSOS", "1 un.", "6,90"],
    ["7967", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "TERMINAL COMPRESSÃO ILHÓS TUBOLAR 1,00MM (PACOTE C/100UNDS)", "DIVERSOS", "1 un.", "7,20"],
    ["7969", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "TERMINAL COMPRESSÃO ILHÓS TUBOLAR 1,50MM (PACOTE C/100UNDS)", "DIVERSOS", "1 un.", "7,50"],
    ["7970", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "TERMINAL COMPRESSÃO ILHÓS TUBOLAR 2,50MM (PACOTE C/100UNDS)", "DIVERSOS", "1 un.", "8,20"],
    ["7971", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "TERMINAL COMPRESSÃO ILHÓS TUBOLAR 4,00MM (PACOTE C/100UNDS)", "DIVERSOS", "1 un.", "10,50"],
    ["7972", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "TERMINAL COMPRESSÃO ILHÓS TUBOLAR 6,00MM (PACOTE C/100UNDS)", "DIVERSOS", "1 un.", "13,90"],
    ["7980", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "TERMINAL COMPRESSÃO ILHÓS TUBOLAR 10,00MM (PACOTE C/100UNDS)", "DIVERSOS", "1 un.", "19,80"],
    ["7981", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "TERMINAL COMPRESSÃO ILHÓS TUBOLAR 16,00MM (PACOTE C/100UNDS)", "DIVERSOS", "1 un.", "29,90"],
    ["7982", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "TERMINAL COMPRESSÃO OLHAL 10MM FURO 1/4\" (PACOTE C/50UNDS)", "DIVERSOS", "1 un.", "18,90"],
    ["7983", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "TERMINAL COMPRESSÃO OLHAL 16MM FURO 1/4\" (PACOTE C/50UNDS)", "DIVERSOS", "1 un.", "24,80"],
    ["7984", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "TERMINAL COMPRESSÃO OLHAL 25MM FURO 5/16\" (PACOTE C/50UNDS)", "DIVERSOS", "1 un.", "37,90"],
    ["7985", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "TERMINAL COMPRESSÃO OLHAL 35MM FURO 3/8\" (PACOTE C/50UNDS)", "DIVERSOS", "1 un.", "49,50"],
    ["7986", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "TERMINAL COMPRESSÃO OLHAL 50MM FURO 3/8\" (PACOTE C/25UNDS)", "DIVERSOS", "1 un.", "39,00"],
    ["7987", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "TERMINAL COMPRESSÃO OLHAL 70MM FURO 3/8\" (PACOTE C/25UNDS)", "DIVERSOS", "1 un.", "56,80"],
    ["7988", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "TESOURA DE PODA 8\" C/CABO EMBORRACHADO", "FERTAK", "1 un.", "27,90"],
    ["7989", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "TIMER ANALÓGICO BIVOLT BATERIA MANUAL", "EXATRON", "1 un.", "38,90"],
    ["7990", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "TIMER DIGITAL BIVOLT MULTIFUNÇÃO", "EXATRON", "1 un.", "64,80"],
    ["7991", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "TOMADA DE EMBUTIR 20A SOBREPOR COMPLETA", "PERLEX", "20 un.", "9,20"],
    ["7992", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "TORQUÊS ARMADOR 10\" POLIDA", "FERTAK", "1 un.", "29,90"],
    ["7993", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "TORQUÊS ARMADOR 12\" POLIDA", "FERTAK", "1 un.", "34,90"],
    ["7994", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "TORNEIRA ELÉTRICA LUMEN 127V 5.500W BRANCA", "HYDRA", "1 un.", "189,00"],
    ["7995", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "TORNEIRA ELÉTRICA LUMEN 220V 5.500W BRANCA", "HYDRA", "1 un.", "189,00"],
    ["7996", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "TORNEIRA ELÉTRICA VERSÁTIL 127V 5.500W BRANCA", "LORENZETTI", "1 un.", "179,00"],
    ["7997", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "TORNEIRA ELÉTRICA VERSÁTIL 220V 5.500W BRANCA", "LORENZETTI", "1 un.", "179,00"],
    ["7998", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "TRANSFORMADOR TRAFO 127V/220V 300VA", "FIOLUX", "1 un.", "79,00"],
    ["7999", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "TRANSFORMADOR TRAFO 127V/220V 500VA", "FIOLUX", "1 un.", "99,00"],
    ["8000", "Materiais Elétricos PAMPULHA", "Materiais Elétricos e Ferramentas", "TRANSFORMADOR TRAFO 127V/220V 1000VA", "FIOLUX", "1 un.", "159,00"]
]

with open('public/modelos/material_eletrico_pampulha.csv', 'a', encoding='utf-8', newline='') as f:
    writer = csv.writer(f)
    writer.writerows(rows)

print(f"Páginas 13 a 16 adicionadas: {len(rows)} itens.")
